//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserSQL.Data.EDMX.TSSecurity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TecserDataS : DbContext
    {
        public TecserDataS()
            : base("name=TecserDataS")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T0001_TRANSACTIONS> T0001_TRANSACTIONS { get; set; }
        public virtual DbSet<TLogTcode> TLogTcode { get; set; }
        public virtual DbSet<TSecRole> TSecRole { get; set; }
        public virtual DbSet<TSecRoleAssignment> TSecRoleAssignment { get; set; }
        public virtual DbSet<TSecurityLog> TSecurityLog { get; set; }
        public virtual DbSet<TsecurityLogCheck> TsecurityLogCheck { get; set; }
        public virtual DbSet<TSecUsr> TSecUsr { get; set; }
    }
}
