//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAE
    {
        public string CAE1 { get; set; }
        public Nullable<System.DateTime> CAE_Vto { get; set; }
        public string FacProv { get; set; }
        public bool Activa { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Cliente { get; set; }
        public Nullable<float> TotPs { get; set; }
        public string Idtrto { get; set; }
        public Nullable<float> ButPs { get; set; }
        public Nullable<float> IvaPs { get; set; }
        public bool EnviadaAFIP { get; set; }
        public bool Confirmada { get; set; }
        public string CUIT { get; set; }
        public string Pto_Vta { get; set; }
    }
}
