//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM01XP
    {
        public int CRMID { get; set; }
        public Nullable<System.DateTime> FechaR { get; set; }
        public string UsuarioR { get; set; }
        public string Tipo { get; set; }
        public bool TieneID { get; set; }
        public string IDCliente { get; set; }
        public string IDProveedor { get; set; }
        public string TxtLlamante { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public bool Cerrado { get; set; }
        public string UsuarioCierre { get; set; }
    }
}
