//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM02XP
    {
        public Nullable<int> CRMID { get; set; }
        public Nullable<short> IDINTERNO { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public string Tipo { get; set; }
        public string TxtLlamante { get; set; }
        public Nullable<double> ID { get; set; }
        public string ModoComunicacion { get; set; }
        public string Motivo { get; set; }
        public bool EsNuevoPedido { get; set; }
        public string IDPedidoNuevo { get; set; }
        public bool EsConsultaMSG { get; set; }
        public bool RDevolverMSG { get; set; }
        public string MensajeRecibido { get; set; }
        public bool NuevoPedido { get; set; }
        public string MensajeEntregado { get; set; }
        public string PedidoMSG { get; set; }
        public string USRLog { get; set; }
        public Nullable<System.DateTime> DateLog { get; set; }
    }
}
