//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int ErrorID { get; set; }
        public string ErrorRow { get; set; }
        public string ErrorMessage { get; set; }
        public string ErrorIssuingPackage { get; set; }
        public string ErrorSourceTable { get; set; }
        public string ErrorDestinationTable { get; set; }
        public Nullable<System.DateTime> ErrorLoggingTime { get; set; }
    }
}
