//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0007_CLI_ENTREGA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0007_CLI_ENTREGA()
        {
            this.T0045_OV_HEADER = new HashSet<T0045_OV_HEADER>();
            this.T0055_REMITO_H = new HashSet<T0055_REMITO_H>();
            this.T0059_ENTREGAS = new HashSet<T0059_ENTREGAS>();
        }
    
        public int ID_CLI_ENTREGA { get; set; }
        public int IDCLIENTE { get; set; }
        public string ClienteEntregaDesc { get; set; }
        public string Direccion_Entrega { get; set; }
        public string DireEntre_Localidad { get; set; }
        public string DireEntre_Provincia { get; set; }
        public string Telefono_Entrega { get; set; }
        public string Pais { get; set; }
        public string Fax { get; set; }
        public string Contacto { get; set; }
        public Nullable<System.DateTime> Fecha_Ingreso { get; set; }
        public Nullable<System.DateTime> Ultimo_Movimiento { get; set; }
        public string DireEntre_Zona { get; set; }
        public string Vendedor { get; set; }
        public Nullable<int> DM_IDTAS { get; set; }
        public bool Activo { get; set; }
        public string Log_User { get; set; }
        public Nullable<System.DateTime> Log_Date { get; set; }
        public string Direccion_EntregaNum { get; set; }
        public string Direccion_EntregaPartido { get; set; }
        public string EntregaHorarios { get; set; }
        public bool CKTRANSPORTE { get; set; }
        public Nullable<int> TRANSPORTE_ID { get; set; }
        public string ZIP { get; set; }
        public bool UNTIPO { get; set; }
        public Nullable<int> IdLocalidadAddress { get; set; }
        public string LogUserModificadoPor { get; set; }
        public Nullable<System.DateTime> LogUserModificadoEn { get; set; }
        public string DireccionGoogleMaps { get; set; }
    
        public virtual T0006_MCLIENTES T0006_MCLIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0045_OV_HEADER> T0045_OV_HEADER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0055_REMITO_H> T0055_REMITO_H { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0059_ENTREGAS> T0059_ENTREGAS { get; set; }
    }
}
