//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0002_LOG
    {
        public int ID { get; set; }
        public string COMPUTER { get; set; }
        public string USER { get; set; }
        public string FE_VERSION { get; set; }
        public string BE_VERSION { get; set; }
        public string FE_PATH { get; set; }
        public string BE_PATH { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    }
}
