//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0001_TRAN
    {
        public string IDTX { get; set; }
        public string TXDesc { get; set; }
        public string Type { get; set; }
        public string num_param { get; set; }
        public string funcion_name { get; set; }
        public string arg1 { get; set; }
        public string arg2 { get; set; }
        public string arg3 { get; set; }
        public string arg4 { get; set; }
        public string arg5 { get; set; }
        public string arg6 { get; set; }
        public string arg7 { get; set; }
        public string MODO { get; set; }
        public bool VISIBLE { get; set; }
        public string USR { get; set; }
        public string XUSRGR { get; set; }
    }
}
