//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0005_MPROVEEDORES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0005_MPROVEEDORES()
        {
            this.T0060_OCOMPRA_H = new HashSet<T0060_OCOMPRA_H>();
            this.T0063_ITEMS_OC_INGRESADOS = new HashSet<T0063_ITEMS_OC_INGRESADOS>();
            this.T0065_MATERIAL_PROVEEDOR = new HashSet<T0065_MATERIAL_PROVEEDOR>();
            this.T0066_ITEMS_PROVEEDOR_OC = new HashSet<T0066_ITEMS_PROVEEDOR_OC>();
            this.T0203_CTACTE_PROV = new HashSet<T0203_CTACTE_PROV>();
            this.T0204_CTACTESALDOS_PROV = new HashSet<T0204_CTACTESALDOS_PROV>();
            this.T0210_OP_H = new HashSet<T0210_OP_H>();
            this.T0406_RendicionFF_H = new HashSet<T0406_RendicionFF_H>();
            this.T0210_OrdenPagoHeader = new HashSet<T0210_OrdenPagoHeader>();
        }
    
        public int id_prov { get; set; }
        public string TIPO { get; set; }
        public string prov_rsocial { get; set; }
        public string prov_fantasia { get; set; }
        public string Direccion { get; set; }
        public string Dire_Localidad { get; set; }
        public string Dire_Provincia { get; set; }
        public string Dire_CodPostal { get; set; }
        public string Dire_Pais { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string Contacto { get; set; }
        public Nullable<int> Cliente { get; set; }
        public string TTAX1 { get; set; }
        public string NTAX1 { get; set; }
        public string TTAX2 { get; set; }
        public string NTAX2 { get; set; }
        public string TTAX3 { get; set; }
        public string NTAX3 { get; set; }
        public Nullable<System.DateTime> Fecha_Ingreso { get; set; }
        public Nullable<System.DateTime> Ultimo_Movimiento { get; set; }
        public string DMTAS { get; set; }
        public string IDRAF { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> REMITO { get; set; }
        public string ZTERM { get; set; }
        public string CONDI_IVA { get; set; }
        public string GL { get; set; }
        public string LOG_USER { get; set; }
        public Nullable<System.DateTime> LOG_DATE { get; set; }
        public string BANK_ACC { get; set; }
        public string COMENTARIO { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
        public Nullable<int> IdLocalidadAddress { get; set; }
        public string Partido { get; set; }
    
        public virtual T0014_TIPO_PROVEEDOR T0014_TIPO_PROVEEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0060_OCOMPRA_H> T0060_OCOMPRA_H { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0063_ITEMS_OC_INGRESADOS> T0063_ITEMS_OC_INGRESADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0065_MATERIAL_PROVEEDOR> T0065_MATERIAL_PROVEEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0066_ITEMS_PROVEEDOR_OC> T0066_ITEMS_PROVEEDOR_OC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0203_CTACTE_PROV> T0203_CTACTE_PROV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0204_CTACTESALDOS_PROV> T0204_CTACTESALDOS_PROV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0210_OP_H> T0210_OP_H { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0406_RendicionFF_H> T0406_RendicionFF_H { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0210_OrdenPagoHeader> T0210_OrdenPagoHeader { get; set; }
    }
}
