//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0004_ASN
    {
        public string XYEAR { get; set; }
        public string TIPO { get; set; }
        public Nullable<short> ASN { get; set; }
        public string XDOC { get; set; }
        public string PRE { get; set; }
        public Nullable<decimal> NASX1X2 { get; set; }
    }
}
