//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0013_COLORES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0013_COLORES()
        {
            this.T0010_MATERIALES = new HashSet<T0010_MATERIALES>();
        }
    
        public string ID_COLOR { get; set; }
        public string DESCRIP_COLOR { get; set; }
        public string UltimoCodigoAsignado { get; set; }
        public Nullable<int> UltimoNumeroAsignado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0010_MATERIALES> T0010_MATERIALES { get; set; }
    }
}
