//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0010_Container
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0010_Container()
        {
            this.T0011_MATERIALES_AKA = new HashSet<T0011_MATERIALES_AKA>();
        }
    
        public string ContainerId { get; set; }
        public string ContainerDescription { get; set; }
        public decimal Capacidad { get; set; }
        public string Medida { get; set; }
        public string Unidad { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0011_MATERIALES_AKA> T0011_MATERIALES_AKA { get; set; }
    }
}
