//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0011_MATERIALES_AKA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0011_MATERIALES_AKA()
        {
            this.T0047_MATERIAL_CLIENTE = new HashSet<T0047_MATERIAL_CLIENTE>();
        }
    
        public string PRIMARIO { get; set; }
        public string CODVENTA { get; set; }
        public string MAT_DESC2 { get; set; }
        public string MAT_DESC_L5 { get; set; }
        public bool ACTIVO { get; set; }
        public string TIPO_MATERIAL { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string LOGUSER { get; set; }
        public string GLV { get; set; }
        public string Container { get; set; }
    
        public virtual T0010_Container T0010_Container { get; set; }
        public virtual T0010_MATERIALES T0010_MATERIALES { get; set; }
        public virtual T0011_MaterialType T0011_MaterialType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0047_MATERIAL_CLIENTE> T0047_MATERIAL_CLIENTE { get; set; }
    }
}
