//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0011_MaterialType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0011_MaterialType()
        {
            this.T0010_MATERIALES = new HashSet<T0010_MATERIALES>();
            this.T0011_MATERIALES_AKA = new HashSet<T0011_MATERIALES_AKA>();
        }
    
        public string Mtype { get; set; }
        public string Descripcion { get; set; }
        public bool Activo { get; set; }
        public bool ControlStock { get; set; }
        public bool ControlCosto { get; set; }
        public bool DispSalesOrder { get; set; }
        public bool DispOrdenCompra { get; set; }
        public bool DispOrdenFabricacion { get; set; }
        public bool DispBOMItem { get; set; }
        public string DefaultUoM { get; set; }
        public string Documentacion { get; set; }
        public string GLInvetory { get; set; }
        public string GLVentas { get; set; }
        public string SLocDefault { get; set; }
        public string OrigenDefault { get; set; }
        public string MaterialPrefix { get; set; }
        public decimal CostoMultiplicador { get; set; }
        public decimal CostoAdicional { get; set; }
        public string GeneraDoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0010_MATERIALES> T0010_MATERIALES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0011_MATERIALES_AKA> T0011_MATERIALES_AKA { get; set; }
    }
}
