//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0010_PARTIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0010_PARTIDO()
        {
            this.T0010_LOCALIDAD = new HashSet<T0010_LOCALIDAD>();
        }
    
        public int Id { get; set; }
        public int IdProvincia { get; set; }
        public string Partido { get; set; }
    
        public virtual T0008_REGION T0008_REGION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0010_LOCALIDAD> T0010_LOCALIDAD { get; set; }
    }
}
