//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0016_PLANTAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0016_PLANTAS()
        {
            this.T0028_SLOC = new HashSet<T0028_SLOC>();
        }
    
        public string IDPLTN { get; set; }
        public string PLTNNAME { get; set; }
        public string PLTNDIRECCION { get; set; }
        public string PLTNLOCALIDAD { get; set; }
        public string PLTNPROVINCIA { get; set; }
        public string SUCREL1 { get; set; }
        public string SUCREL2 { get; set; }
        public string REF_REL1 { get; set; }
        public string REF_REL2 { get; set; }
        public Nullable<bool> Activa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0028_SLOC> T0028_SLOC { get; set; }
    }
}
