//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0010_MATERIALES_NCD
    {
        public string IDITEM { get; set; }
        public string DESCRIPCION { get; set; }
        public string GLV { get; set; }
        public string GLI { get; set; }
        public bool DISPNC { get; set; }
        public bool DISPND { get; set; }
        public bool ACTIVO { get; set; }
    }
}
