//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0015_TIPO_FACTURA
    {
        public string IDFACT { get; set; }
        public string IDDOC { get; set; }
        public string TIPOFACT { get; set; }
        public string Denominacion { get; set; }
        public string DFACT { get; set; }
        public string CUENTA { get; set; }
        public bool VENTA { get; set; }
        public bool COMPRA { get; set; }
        public string ID_AFIP { get; set; }
        public string COD_DOC { get; set; }
    }
}
