//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0017_CONDIVA
    {
        public string COD_AFIP { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> ALICUOTA { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    }
}
