//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0019_ZTERM
    {
        public string ZTERM { get; set; }
        public string ZTERMDESC { get; set; }
        public int ZTERMDIASCOB { get; set; }
        public int ZTERMDIASPPM { get; set; }
        public bool ACTIVO { get; set; }
    }
}
