//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0014_TIPO_PROVEEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0014_TIPO_PROVEEDOR()
        {
            this.T0005_MPROVEEDORES = new HashSet<T0005_MPROVEEDORES>();
        }
    
        public string TIPOPROV { get; set; }
        public string TIPOPROV_DESC { get; set; }
        public bool EntregaRemito { get; set; }
        public bool FacturaA { get; set; }
        public bool FacturaB { get; set; }
        public bool FacturaC { get; set; }
        public bool FacturaE { get; set; }
        public bool FacturaM { get; set; }
        public bool DISPO_OC { get; set; }
        public bool DISPO_NOC { get; set; }
        public string CC_DEFAULT { get; set; }
        public bool DISPO_XREG { get; set; }
        public string GL { get; set; }
        public bool Activo { get; set; }
        public int RangoIDProveedor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0005_MPROVEEDORES> T0005_MPROVEEDORES { get; set; }
    }
}
