//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0017_TaxModuleAssign
    {
        public string CP { get; set; }
        public int IdNumero { get; set; }
        public string IdTax { get; set; }
        public bool Exento { get; set; }
        public string Certificado { get; set; }
        public System.DateTime FechaDesde { get; set; }
        public System.DateTime FechaHasta { get; set; }
        public string Ntax { get; set; }
    
        public virtual T0016_TaxModuleDefinition T0016_TaxModuleDefinition { get; set; }
    }
}
