//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0029_ESTADO_STOCK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0029_ESTADO_STOCK()
        {
            this.T0030_STOCK = new HashSet<T0030_STOCK>();
        }
    
        public int IDESTADO { get; set; }
        public string ESTADO { get; set; }
        public string DESCRIPCION { get; set; }
        public bool DefaultStateIP { get; set; }
        public bool DefualtStateIC { get; set; }
        public bool AllowStateChangeCQ { get; set; }
        public bool AllowKGChangeCQ { get; set; }
        public bool AvailableStateForIP { get; set; }
        public bool StockAvailable { get; set; }
        public bool AvailableStateForIC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0030_STOCK> T0030_STOCK { get; set; }
    }
}
