//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0021_FORMULA_I
    {
        public int ID_ITEM { get; set; }
        public int FORMULA { get; set; }
        public string ITEM { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public Nullable<decimal> CANTIDAD_PORC { get; set; }
        public string UNIDAD { get; set; }
        public Nullable<int> DMIGRA_ID { get; set; }
        public Nullable<int> Secuencia { get; set; }
        public bool Explota { get; set; }
        public Nullable<int> ExplotaVer { get; set; }
    
        public virtual T0010_MATERIALES T0010_MATERIALES { get; set; }
        public virtual T0020_FORMULA_H T0020_FORMULA_H { get; set; }
    }
}
