//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0020_FORMULA_H
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0020_FORMULA_H()
        {
            this.T0021_FORMULA_I = new HashSet<T0021_FORMULA_I>();
        }
    
        public int ID_FORMULA { get; set; }
        public string IDMATERIAL { get; set; }
        public string NEL { get; set; }
        public string DESC_FORMULA { get; set; }
        public string FORM_VERSION { get; set; }
        public Nullable<System.DateTime> FORM_FECHA { get; set; }
        public Nullable<System.DateTime> FORM_MODIF { get; set; }
        public Nullable<bool> ACTIVA { get; set; }
        public string COLOR { get; set; }
        public string STATUS { get; set; }
        public string DESARROLLADO { get; set; }
        public string USER { get; set; }
        public Nullable<decimal> BATCH_SIZE { get; set; }
        public Nullable<bool> FControloda { get; set; }
        public Nullable<System.DateTime> FControlFecha { get; set; }
        public string FControlResp { get; set; }
        public Nullable<System.DateTime> LastUsed { get; set; }
        public Nullable<int> Dureza { get; set; }
        public string IndicacionFabricacion { get; set; }
        public Nullable<int> TiempoMezclado { get; set; }
        public string PlanInspeccion { get; set; }
        public string NotasQA { get; set; }
        public string MasterRecipe { get; set; }
        public string LogUpdatedBy { get; set; }
        public bool F4D { get; set; }
    
        public virtual T0010_MATERIALES T0010_MATERIALES { get; set; }
        public virtual T0010_MATERIALES T0010_MATERIALES1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0021_FORMULA_I> T0021_FORMULA_I { get; set; }
    }
}
