//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0038_CostoMfgExplo
    {
        public string MaterialFabricar { get; set; }
        public string MaterialItem { get; set; }
        public int FormulaId { get; set; }
        public int IdItemFormula { get; set; }
        public string Origen { get; set; }
        public string MonedaItem { get; set; }
        public decimal CostoARS { get; set; }
        public decimal CostoUSD { get; set; }
        public decimal FormulaProp { get; set; }
        public decimal PropARS { get; set; }
        public decimal PropUSD { get; set; }
        public string TipoCosto { get; set; }
        public System.DateTime FechaCostoItem { get; set; }
        public System.DateTime LastRun { get; set; }
    
        public virtual T0037_CostoMfg T0037_CostoMfg { get; set; }
    }
}
