//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0039_REPOHISTORY
    {
        public int Id { get; set; }
        public string Material { get; set; }
        public int VendorId { get; set; }
        public string VendorRS { get; set; }
        public System.DateTime FechaFactura { get; set; }
        public Nullable<int> IdFactura { get; set; }
        public int IdItem { get; set; }
        public string Moneda { get; set; }
        public decimal KG { get; set; }
        public decimal PrecioArs { get; set; }
        public decimal PrecioUsd { get; set; }
        public bool VisibleRepo { get; set; }
        public bool UpdateManual { get; set; }
        public Nullable<System.DateTime> UpdateFecha { get; set; }
        public string UpdateUser { get; set; }
    }
}
