//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0039_CostoStandard
    {
        public string Material { get; set; }
        public string Origen { get; set; }
        public string MType { get; set; }
        public string MonedaCosto { get; set; }
        public string CostDetBy { get; set; }
        public System.DateTime FechaCosto { get; set; }
        public decimal CostoArs { get; set; }
        public decimal CostoUsd { get; set; }
        public decimal CostoArsOld { get; set; }
        public decimal CostoUsdOld { get; set; }
        public decimal VarCostoArs { get; set; }
        public decimal VarCostoUsd { get; set; }
        public System.DateTime FechaCostoOld { get; set; }
        public bool ManualUpdated { get; set; }
        public System.DateTime FechaCostRoll { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public decimal DeltaUsd1 { get; set; }
        public decimal DeltaUsd2 { get; set; }
    }
}
