//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0034_CostRollHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0034_CostRollHeader()
        {
            this.T0035_CostRoll = new HashSet<T0035_CostRoll>();
        }
    
        public System.Guid idCostRoll { get; set; }
        public System.DateTime FechaCostRoll { get; set; }
        public string UserRun { get; set; }
        public string Machinerun { get; set; }
        public bool VersionActiva { get; set; }
        public string Comentario { get; set; }
        public Nullable<decimal> RunTimeCompras { get; set; }
        public Nullable<decimal> RunTimeFabricado { get; set; }
        public Nullable<decimal> RunTimeExplosion { get; set; }
        public Nullable<bool> UpdCompras { get; set; }
        public Nullable<bool> UpdFabricado { get; set; }
        public bool Temporal { get; set; }
        public bool MPFinalizado { get; set; }
        public bool PTFinalizado { get; set; }
        public bool StandardSet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0035_CostRoll> T0035_CostRoll { get; set; }
    }
}
