//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0031_STOCK_CHG
    {
        public int IDCHG { get; set; }
        public string MATERIAL { get; set; }
        public string LOTEFIRST { get; set; }
        public string LOTEORI { get; set; }
        public Nullable<int> KGORI { get; set; }
        public string LOTENEW { get; set; }
        public string KGNEW { get; set; }
        public Nullable<int> IDPROV { get; set; }
        public string PROV { get; set; }
        public Nullable<System.DateTime> LOGDATE { get; set; }
        public string LOGUSER { get; set; }
    }
}
