//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0036_CostoReposicion
    {
        public string Material { get; set; }
        public string Origen { get; set; }
        public decimal KgUC { get; set; }
        public string MonedaCosto { get; set; }
        public decimal TCConversion { get; set; }
        public decimal CostoUCArs { get; set; }
        public decimal CostoUCUsd { get; set; }
        public int ProveedorID { get; set; }
        public System.DateTime FechaUC { get; set; }
        public decimal CostoPPPArs { get; set; }
        public decimal CostoPPPUsd { get; set; }
        public decimal VarCostoUCArs { get; set; }
        public decimal VarCostoUCUsd { get; set; }
        public System.DateTime FechaCompraAnterior { get; set; }
        public string UserConta { get; set; }
        public bool ManualUpdated { get; set; }
        public string UserManualUpd { get; set; }
        public Nullable<System.DateTime> DateManualUpd { get; set; }
        public bool CostoUpdatedCostRoll { get; set; }
        public bool UpdatedAfterCR { get; set; }
    }
}
