//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0037_CostRollExplosionL1
    {
        public string ProductoFabricado { get; set; }
        public int FormulaID { get; set; }
        public int MaterialID { get; set; }
        public string MaterialComponente { get; set; }
        public string OrigenComponente { get; set; }
        public string MonedaCosto { get; set; }
        public decimal Proporcion { get; set; }
        public decimal CostoRepoArs { get; set; }
        public decimal CostoRepoUsd { get; set; }
        public decimal CostoStdArs { get; set; }
        public decimal CostoStdUsd { get; set; }
        public System.DateTime FechaCosto { get; set; }
        public bool ManualUpdStd { get; set; }
        public bool ManualUpdRepo { get; set; }
        public string FlagStd { get; set; }
        public string FlagRepo { get; set; }
        public bool MaterialActivo { get; set; }
        public int FormulaComplex { get; set; }
        public decimal CostoStdArsProp { get; set; }
        public decimal CostoStdUsdProp { get; set; }
        public decimal CostoRepoArsProp { get; set; }
        public decimal CostoRepoUsdProp { get; set; }
    }
}
