//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0037_CostoMfg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0037_CostoMfg()
        {
            this.T0038_CostoMfgExplo = new HashSet<T0038_CostoMfgExplo>();
        }
    
        public string Material { get; set; }
        public string Origen { get; set; }
        public int LevelMax { get; set; }
        public string MonedaCosto { get; set; }
        public decimal TCCalculo { get; set; }
        public int FCost { get; set; }
        public decimal MfgArsStd { get; set; }
        public decimal MfgUsdStd { get; set; }
        public decimal MfgArsRepo { get; set; }
        public decimal MfgUsdRepo { get; set; }
        public System.DateTime CostDateStd { get; set; }
        public System.DateTime CostDateRepo { get; set; }
        public System.DateTime UpdateFCost { get; set; }
        public System.DateTime LastRun { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0038_CostoMfgExplo> T0038_CostoMfgExplo { get; set; }
    }
}
