//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0041_LOG_CAMBIOS_NP
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string USER { get; set; }
        public Nullable<int> IDOV { get; set; }
        public Nullable<int> IDITEM { get; set; }
        public string MATERIAL { get; set; }
        public Nullable<int> CLIENTE { get; set; }
        public string CAMPO { get; set; }
        public string VALOR_A { get; set; }
        public string VALOR_N { get; set; }
    }
}
