//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0042_MM40_CONFIG
    {
        public string TXLEVEL { get; set; }
        public string TX { get; set; }
        public string TX2 { get; set; }
        public string TDESCRIPCION { get; set; }
        public string UGROUP { get; set; }
        public bool BUSQUEDA { get; set; }
    }
}
