//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0047_MATERIAL_CLIENTE
    {
        public int CLIENTE { get; set; }
        public string MATERIAL { get; set; }
        public string MATERIAL_CLI { get; set; }
        public Nullable<System.DateTime> FULTIMACOMPRA { get; set; }
        public Nullable<decimal> ULTIMACANTIDAD { get; set; }
        public string MONEDAUCOMPRA { get; set; }
        public Nullable<decimal> ULTIMOPRECIO { get; set; }
        public Nullable<decimal> ULTIMOTC { get; set; }
        public Nullable<int> CALIFICACION { get; set; }
        public string COMENTARIO { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
        public Nullable<System.DateTime> FECHA_MODI_PRECIO { get; set; }
        public Nullable<System.DateTime> FECHA_ALTA { get; set; }
        public string FLAG_ALTA { get; set; }
        public Nullable<decimal> PrecioAnterior { get; set; }
        public Nullable<System.DateTime> FechaModificacionAnterior { get; set; }
        public string MonedaAnteriorCotizacion { get; set; }
        public string modo { get; set; }
        public Nullable<decimal> PRECIO1 { get; set; }
        public Nullable<decimal> PRECIO2 { get; set; }
    
        public virtual T0011_MATERIALES_AKA T0011_MATERIALES_AKA { get; set; }
    }
}
