//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0040_MAT_MOVIMIENTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0040_MAT_MOVIMIENTOS()
        {
            this.T0042_PRODUCCION_DET = new HashSet<T0042_PRODUCCION_DET>();
        }
    
        public int IDMOVIMIENTO { get; set; }
        public string IDMATERIAL { get; set; }
        public Nullable<int> TIPOMOVIMIENTO { get; set; }
        public Nullable<System.DateTime> FECHAMOV { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public string DOCUMENTO { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public string BATCH { get; set; }
        public string LOG_USER { get; set; }
        public Nullable<System.DateTime> LOG_DATE { get; set; }
        public string COMENTARIO { get; set; }
        public string TIPO { get; set; }
        public string IET { get; set; }
        public string PERIODO { get; set; }
        public string TCODE { get; set; }
        public string SLOC { get; set; }
        public string BATCHST { get; set; }
        public Nullable<int> IDCLI { get; set; }
        public Nullable<int> IDPRO { get; set; }
        public string XTABLA { get; set; }
        public string XIDTXT { get; set; }
        public Nullable<int> XIDNUM { get; set; }
        public Nullable<int> RECURSO { get; set; }
        public string TXT1 { get; set; }
        public string GLVTA { get; set; }
        public Nullable<decimal> NAS1 { get; set; }
        public Nullable<decimal> NAS2 { get; set; }
    
        public virtual T0080_TIPO_MOVIMIENTOS T0080_TIPO_MOVIMIENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0042_PRODUCCION_DET> T0042_PRODUCCION_DET { get; set; }
    }
}
