//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0059_HOJARUTA_I
    {
        public int IdRuta { get; set; }
        public int IdItem { get; set; }
        public Nullable<int> IdRemito { get; set; }
        public string NumeroRemito { get; set; }
        public string ClienteRazonSocial { get; set; }
        public string DireccionCompleta { get; set; }
        public Nullable<decimal> KgEntregados { get; set; }
        public bool EntregaMuestra { get; set; }
        public bool RetiraPago { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> CantidadBultos { get; set; }
        public Nullable<bool> CargoCliente { get; set; }
        public Nullable<decimal> Prorrateo { get; set; }
        public string StatusEntrega { get; set; }
        public Nullable<int> OrdenEntrega { get; set; }
    
        public virtual T0055_REMITO_H T0055_REMITO_H { get; set; }
        public virtual T0059_HOJARUTA_H T0059_HOJARUTA_H { get; set; }
    }
}
