//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0059_HOJARUTA_H
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0059_HOJARUTA_H()
        {
            this.T0059_ENTREGAS = new HashSet<T0059_ENTREGAS>();
            this.T0059_HOJARUTA_I = new HashSet<T0059_HOJARUTA_I>();
        }
    
        public int IdRuta { get; set; }
        public Nullable<int> IdEmpresaFlete { get; set; }
        public string EmpresaFlete { get; set; }
        public string DescripcionFlete { get; set; }
        public Nullable<System.DateTime> FechaDespacho { get; set; }
        public string Chofer { get; set; }
        public Nullable<System.DateTime> HoraSalida { get; set; }
        public Nullable<System.DateTime> HoraLlegada { get; set; }
        public Nullable<decimal> CostoFlete { get; set; }
        public string StatusRuta { get; set; }
        public string LogUser { get; set; }
        public System.DateTime LogFecha { get; set; }
        public Nullable<System.DateTime> LogCierreFecha { get; set; }
        public string LogCierreUser { get; set; }
        public string Matricula { get; set; }
        public Nullable<decimal> KmRecorridos { get; set; }
        public string TipoEnvio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0059_ENTREGAS> T0059_ENTREGAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0059_HOJARUTA_I> T0059_HOJARUTA_I { get; set; }
    }
}
