//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0050_REQUISICION
    {
        public int IDREQUISICION { get; set; }
        public Nullable<System.DateTime> FechaRequisicion { get; set; }
        public string ItemMaterialMaster { get; set; }
        public string DescripcionItem { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public string UnidadCompra { get; set; }
        public string EstadoRequisicion { get; set; }
        public string Comentario { get; set; }
        public string LogUsuario { get; set; }
        public Nullable<int> ProveedorRecomendado { get; set; }
        public Nullable<decimal> PrecioAproximado { get; set; }
        public Nullable<bool> PROV_MAT { get; set; }
        public Nullable<int> OC_CONTROL { get; set; }
        public Nullable<System.DateTime> LogFecha { get; set; }
        public string UsuarioSolicitud { get; set; }
        public string AprobadoUsuario { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public string AprobadoEstado { get; set; }
        public bool Aprobado { get; set; }
    
        public virtual T0010_MATERIALES T0010_MATERIALES { get; set; }
    }
}
