//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0059_LOGSDPROCESS
    {
        public int idLog { get; set; }
        public Nullable<int> idRemito { get; set; }
        public string NumeroRemito { get; set; }
        public Nullable<int> idFactura { get; set; }
        public string NumeroFactura { get; set; }
        public Nullable<int> idRuta { get; set; }
        public Nullable<System.DateTime> RemitoStart { get; set; }
        public Nullable<System.DateTime> RemitoAPreparacion { get; set; }
        public Nullable<System.DateTime> RemitoPreparado { get; set; }
        public Nullable<System.DateTime> RemitoImpresion { get; set; }
        public Nullable<System.DateTime> FacturaContabilizacion { get; set; }
        public Nullable<System.DateTime> HojaRutaImpresion { get; set; }
    }
}
