//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0057_REMITO_I_PRINT
    {
        public string IDMATERIAL { get; set; }
        public int IDREMITO { get; set; }
        public int IDITEM { get; set; }
        public string NUMREMITO { get; set; }
        public string DESC_REMITO { get; set; }
        public Nullable<decimal> KGDESPACHADOS_R { get; set; }
        public string MONEDA { get; set; }
        public Nullable<decimal> PRECIOU { get; set; }
        public Nullable<decimal> PRECIOT { get; set; }
        public Nullable<decimal> TC_FACTU { get; set; }
        public string BATCH_REMITO { get; set; }
        public Nullable<bool> VISIBLE_RE { get; set; }
        public Nullable<bool> VISIBLE_FA { get; set; }
        public Nullable<bool> IVA21 { get; set; }
        public string GLV { get; set; }
        public string GLI { get; set; }
    }
}
