//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0057_DESPACHOS_TEMP
    {
        public int ID { get; set; }
        public Nullable<int> IDDESPACHO { get; set; }
        public string CLIRZ { get; set; }
        public string CLIENT { get; set; }
        public Nullable<int> CodClienteEntrega { get; set; }
        public Nullable<int> IDOV { get; set; }
        public Nullable<System.DateTime> FechaCompromiso { get; set; }
        public Nullable<int> IDITEM { get; set; }
        public string MATERIAL { get; set; }
        public Nullable<decimal> KGPEDIDO { get; set; }
        public Nullable<decimal> KGRESTANTE { get; set; }
        public Nullable<decimal> KGSTOCKC { get; set; }
        public Nullable<decimal> KGSTOCKD { get; set; }
        public string StatusEntregaFecha { get; set; }
        public string StatusEntregaItem { get; set; }
        public string ModoEntrega { get; set; }
        public Nullable<System.DateTime> FechaOV { get; set; }
    }
}
