//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0056_REMITO_I
    {
        public int IDREMITO { get; set; }
        public int IDITEM { get; set; }
        public string NUMREMITO { get; set; }
        public string MATERIAL { get; set; }
        public string MATERIALAKA { get; set; }
        public string DESC_REMITO { get; set; }
        public decimal KGINI { get; set; }
        public decimal KGDESPACHADOS { get; set; }
        public decimal KGDESPACHADOS_R { get; set; }
        public string STATUSITEM { get; set; }
        public string MONEDA { get; set; }
        public Nullable<decimal> PRECIOU { get; set; }
        public Nullable<decimal> PRECIOT { get; set; }
        public Nullable<decimal> PRECIOU_USD { get; set; }
        public Nullable<decimal> PRECIOT_USD { get; set; }
        public Nullable<decimal> PRECIOU_ARS { get; set; }
        public Nullable<decimal> PRECIOT_ARS { get; set; }
        public Nullable<decimal> TC_FACTU { get; set; }
        public Nullable<bool> GENERAR_REMITO { get; set; }
        public Nullable<int> IDOV { get; set; }
        public Nullable<int> IDOVITEM { get; set; }
        public string BATCH { get; set; }
        public string BATCH_REMITO { get; set; }
        public Nullable<decimal> KG_PENDIENTES { get; set; }
        public Nullable<bool> STOCK_COMPRO { get; set; }
        public Nullable<int> RLINK { get; set; }
        public bool VISIBLE_RE { get; set; }
        public bool VISIBLE_FA { get; set; }
        public bool IVA21 { get; set; }
        public string GL { get; set; }
        public string GLV { get; set; }
        public string LX { get; set; }
        public bool L5 { get; set; }
        public Nullable<int> idStockComprometido { get; set; }
        public string SLOC { get; set; }
    
        public virtual T0055_REMITO_H T0055_REMITO_H { get; set; }
    }
}
