//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0061_OCOMPRA_I
    {
        public int IDITEMCOMPRA { get; set; }
        public int ORDENCOMPRA { get; set; }
        public string MATERIAL { get; set; }
        public string MATERIAL_PROVEEDOR { get; set; }
        public Nullable<int> REQUISICION { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public Nullable<decimal> CANTIDAD_RECIBIDA { get; set; }
        public string REMITO { get; set; }
        public Nullable<System.DateTime> FECHARECIBIDO { get; set; }
        public Nullable<decimal> PRECIOBASE { get; set; }
        public Nullable<decimal> PRECIO_UNITARIO_P { get; set; }
        public Nullable<decimal> PRECIO_UNITARIO_D { get; set; }
        public Nullable<decimal> TC { get; set; }
        public string StatusItem { get; set; }
        public string ComentarioI_OC { get; set; }
        public string ComentarioI_RE { get; set; }
        public Nullable<bool> ALLRC { get; set; }
        public Nullable<int> IdRC { get; set; }
        public Nullable<int> IdRCItem { get; set; }
    
        public virtual T0010_MATERIALES T0010_MATERIALES { get; set; }
        public virtual T0060_OCOMPRA_H T0060_OCOMPRA_H { get; set; }
    }
}
