//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0068RequisicionCompra
    {
        public int idRc { get; set; }
        public System.DateTime FechaRc { get; set; }
        public string UserRc { get; set; }
        public string Material { get; set; }
        public string StatusRc { get; set; }
        public decimal KgStockAuto { get; set; }
        public Nullable<decimal> KgStockRevisado { get; set; }
        public Nullable<decimal> StockMinimo { get; set; }
        public decimal KgRequeridos { get; set; }
        public string ComentarioRc { get; set; }
        public Nullable<int> NumeroOC { get; set; }
        public string AproboOC { get; set; }
        public Nullable<System.DateTime> FechaAproboOC { get; set; }
        public string CometarioOC { get; set; }
        public Nullable<int> ProveedorElegido { get; set; }
        public Nullable<int> ItemOC { get; set; }
    }
}
