//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0066_ITEMS_PROVEEDOR_OC
    {
        public int PROVEEDOR { get; set; }
        public string ITEM { get; set; }
        public string MON { get; set; }
        public Nullable<decimal> PRECIO_U { get; set; }
        public string CentroCosto { get; set; }
        public Nullable<System.DateTime> LOGDATE { get; set; }
        public string LOGUSER { get; set; }
        public string GL { get; set; }
        public string CC { get; set; }
        public Nullable<bool> RECUERDA_PRECIO { get; set; }
        public string GLPATH { get; set; }
    
        public virtual T0005_MPROVEEDORES T0005_MPROVEEDORES { get; set; }
    }
}
