//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0060_OCOMPRA_H
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0060_OCOMPRA_H()
        {
            this.T0061_OCOMPRA_I = new HashSet<T0061_OCOMPRA_I>();
        }
    
        public int IDORDENCOMPRA { get; set; }
        public Nullable<System.DateTime> FECHAOC { get; set; }
        public Nullable<System.DateTime> FECHA_RECIBIDO { get; set; }
        public string STATUSOC { get; set; }
        public Nullable<int> PROVEEDOR { get; set; }
        public string MONEDAOC { get; set; }
        public Nullable<decimal> TotalOC { get; set; }
        public Nullable<decimal> TC { get; set; }
        public string ObservacionOC { get; set; }
        public string LogUser { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
    
        public virtual T0005_MPROVEEDORES T0005_MPROVEEDORES { get; set; }
        public virtual T0151_MONEDAS T0151_MONEDAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0061_OCOMPRA_I> T0061_OCOMPRA_I { get; set; }
    }
}
