//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0065_MATERIAL_PROVEEDOR
    {
        public int PROVEEDOR { get; set; }
        public string MATERIAL_TECSER { get; set; }
        public string MATERIAL_PROVEEDOR { get; set; }
        public Nullable<System.DateTime> FULTIMACOMPRA { get; set; }
        public Nullable<decimal> ULTIMACANTIDAD { get; set; }
        public string MONEDAUCOMPRA { get; set; }
        public Nullable<decimal> ULTIMOPRECIO { get; set; }
        public Nullable<decimal> ULTIMOTC { get; set; }
        public Nullable<int> CALIFICACION { get; set; }
        public string COMENTARIO { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
        public Nullable<bool> REQUIERAQA { get; set; }
        public Nullable<System.DateTime> FECHA_MODI_PRECIO { get; set; }
        public Nullable<System.DateTime> FECHA_ALTA { get; set; }
        public string FLAG_ALTA { get; set; }
    
        public virtual T0005_MPROVEEDORES T0005_MPROVEEDORES { get; set; }
        public virtual T0010_MATERIALES T0010_MATERIALES { get; set; }
    }
}
