//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0078_FASONEXT_I
    {
        public int IDF { get; set; }
        public int IDFItem { get; set; }
        public System.DateTime FechaRecepcion { get; set; }
        public string Remito { get; set; }
        public decimal CantidadRecibida { get; set; }
        public decimal CantidadRemito { get; set; }
        public string MaterialIngreso { get; set; }
        public bool Conta { get; set; }
        public int Id63 { get; set; }
        public string Observacion { get; set; }
    
        public virtual T0063_ITEMS_OC_INGRESADOS T0063_ITEMS_OC_INGRESADOS { get; set; }
        public virtual T0077_FASONEXT_H T0077_FASONEXT_H { get; set; }
    }
}
