//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0075_RESERVA_PF
    {
        public string MATERIAL { get; set; }
        public string MATERIAL_COMODIN { get; set; }
        public string NOTA1 { get; set; }
        public string MATERIAL_RESERVA { get; set; }
        public bool ACTIVO { get; set; }
        public string RESULTADO { get; set; }
        public string LOG_USER { get; set; }
        public Nullable<System.DateTime> LOG_DATE { get; set; }
        public string USUARIO { get; set; }
        public int ID { get; set; }
    }
}
