//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0074_PFLOG
    {
        public int idPlan { get; set; }
        public int idOrden { get; set; }
        public string PlanStatus { get; set; }
        public System.DateTime LogDate { get; set; }
        public string LogUser { get; set; }
        public string Comentario { get; set; }
    
        public virtual T0070_PLANPRODUCCION T0070_PLANPRODUCCION { get; set; }
    }
}
