//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0077_FASONEXT_H
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0077_FASONEXT_H()
        {
            this.T0078_FASONEXT_I = new HashSet<T0078_FASONEXT_I>();
        }
    
        public int IDF { get; set; }
        public string Material { get; set; }
        public int Proveedor { get; set; }
        public string LoteE { get; set; }
        public decimal CantidadE { get; set; }
        public System.DateTime FechaE { get; set; }
        public int ProveedorFason { get; set; }
        public string RemitoE { get; set; }
        public string MaterialARecibir { get; set; }
        public decimal CantidadARecibir { get; set; }
        public decimal CantidadRecibida { get; set; }
        public string StatusFason { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0078_FASONEXT_I> T0078_FASONEXT_I { get; set; }
    }
}
