//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0072_FORMULA_TEMP
    {
        public int OF { get; set; }
        public int idItemFormula { get; set; }
        public int NForm { get; set; }
        public string Primario { get; set; }
        public Nullable<decimal> CantidadBase { get; set; }
        public Nullable<decimal> CantidadKG { get; set; }
        public Nullable<decimal> CantidadPor { get; set; }
        public bool Modificado { get; set; }
        public bool MaterialExtra { get; set; }
        public Nullable<decimal> CantidadKGReal { get; set; }
        public Nullable<decimal> CantidadPorReal { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<decimal> STKLiberado { get; set; }
        public Nullable<decimal> STKTotal { get; set; }
        public Nullable<decimal> STKFinal { get; set; }
        public Nullable<int> Secuencia { get; set; }
        public Nullable<int> idStockReservado { get; set; }
        public string StatusStock { get; set; }
        public Nullable<System.DateTime> LogUltimoChequeo { get; set; }
        public Nullable<System.DateTime> LogCierreES { get; set; }
        public bool Repro { get; set; }
        public bool Added { get; set; }
        public bool Recalculo { get; set; }
    
        public virtual T0070_PLANPRODUCCION T0070_PLANPRODUCCION { get; set; }
    }
}
