//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0070_PLANPRODUCCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0070_PLANPRODUCCION()
        {
            this.T0072_FORMULA_TEMP = new HashSet<T0072_FORMULA_TEMP>();
            this.T0073_FORMULA_PRINT = new HashSet<T0073_FORMULA_PRINT>();
            this.T0074_PFLOG = new HashSet<T0074_PFLOG>();
        }
    
        public int IDPLAN { get; set; }
        public string IDPLAN_S { get; set; }
        public string MATERIAL { get; set; }
        public decimal KG_FABRICAR { get; set; }
        public decimal KG_FABRICAR_O { get; set; }
        public string PLANPARA { get; set; }
        public Nullable<int> OV { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> FPLAN { get; set; }
        public Nullable<System.DateTime> FCOMPROMISO { get; set; }
        public string FLAG { get; set; }
        public string ObsPlan { get; set; }
        public Nullable<int> RECURSO { get; set; }
        public string Operario { get; set; }
        public Nullable<int> Formula { get; set; }
        public Nullable<System.DateTime> FechaFabricacion { get; set; }
        public string ObsPlaneacion { get; set; }
        public decimal KG_Fabricados { get; set; }
        public string NumLote { get; set; }
        public string MATETIQUETA { get; set; }
        public string LogUserPlan { get; set; }
        public Nullable<System.DateTime> LogDatePlan { get; set; }
        public string LogUserForm { get; set; }
        public Nullable<System.DateTime> LogDateForm { get; set; }
        public string LogUserIProd { get; set; }
        public Nullable<System.DateTime> LogDateIProd { get; set; }
        public string CanceledUser { get; set; }
        public string CanceledReason { get; set; }
        public string ComentariosIProd { get; set; }
        public Nullable<int> SecuenciaFAB { get; set; }
        public Nullable<int> CantidadBatches { get; set; }
        public string XLOTE { get; set; }
        public string PLTN { get; set; }
        public string CQLAB { get; set; }
        public Nullable<bool> PRN { get; set; }
        public string CLIENTE { get; set; }
        public string TDOC { get; set; }
        public string Env01 { get; set; }
        public Nullable<int> CantEnv01 { get; set; }
        public string Env02 { get; set; }
        public Nullable<int> CantEnv02 { get; set; }
        public decimal CalculoMP { get; set; }
        public bool AprobadoFabricar { get; set; }
        public string AprobadoFabTcode { get; set; }
        public string AprobadoFabUser { get; set; }
        public Nullable<System.DateTime> AprobadoFabFecha { get; set; }
        public Nullable<System.DateTime> LogRecordInDate { get; set; }
        public string LogRecordInUser { get; set; }
    
        public virtual T0010_MATERIALES T0010_MATERIALES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0072_FORMULA_TEMP> T0072_FORMULA_TEMP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0073_FORMULA_PRINT> T0073_FORMULA_PRINT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0074_PFLOG> T0074_PFLOG { get; set; }
    }
}
