//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0073_FORMULA_PRINT
    {
        public int OF { get; set; }
        public int NForm { get; set; }
        public string Primario { get; set; }
        public Nullable<decimal> CantidadBase { get; set; }
        public Nullable<decimal> CantidadKG { get; set; }
        public Nullable<decimal> CantidadGR { get; set; }
        public Nullable<decimal> DISP_VALUE { get; set; }
        public string DISP_VALUE2 { get; set; }
        public Nullable<decimal> CantidadPor { get; set; }
        public string DISP_UNIT { get; set; }
        public string DISP_UNIT2 { get; set; }
        public Nullable<bool> Modificado { get; set; }
        public Nullable<bool> MaterialExtra { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<int> CantBatches { get; set; }
        public Nullable<int> Secuencia { get; set; }
        public Nullable<int> idItemFormula { get; set; }
        public Nullable<int> idStockReservado { get; set; }
    
        public virtual T0070_PLANPRODUCCION T0070_PLANPRODUCCION { get; set; }
    }
}
