//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0087_HHRR_DISPONIBILIDAD
    {
        public string Shortname { get; set; }
        public bool Venta { get; set; }
        public bool Despacho { get; set; }
        public bool ControlCalidad { get; set; }
        public bool Operario { get; set; }
        public bool Cobranza { get; set; }
        public bool IngresoIC { get; set; }
        public bool Vendedor { get; set; }
        public bool AutorizaSinCargo { get; set; }
    
        public virtual T0085_HHRR_PERSONAL_BASIC T0085_HHRR_PERSONAL_BASIC { get; set; }
    }
}
