//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0085_PERSONAL
    {
        public string ID_VEND { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string SHORTNAME { get; set; }
        public string GL { get; set; }
        public string LEGAJORAF { get; set; }
        public bool ACTIVO { get; set; }
        public string DOCUMENTO { get; set; }
        public string CUIL { get; set; }
        public string CUENTANUMERO { get; set; }
        public string CBU { get; set; }
        public Nullable<decimal> COMISION_VARIABLE { get; set; }
        public Nullable<decimal> COMISION2_FIJA { get; set; }
        public Nullable<bool> PERMITE_VENTA { get; set; }
        public Nullable<bool> PERMITE_DESPACHO { get; set; }
        public Nullable<bool> PERMITE_CCALIDAD { get; set; }
        public Nullable<bool> PERMITE_OPERARIO { get; set; }
        public Nullable<bool> PERMITE_COBRANZA { get; set; }
        public Nullable<bool> PermiteIngresoIC { get; set; }
        public string EMAIL { get; set; }
        public string EMAILCORP { get; set; }
        public Nullable<bool> SYJ { get; set; }
        public Nullable<bool> SYJQ { get; set; }
        public Nullable<int> VENDOR { get; set; }
        public Nullable<System.DateTime> INGRESO { get; set; }
        public string GLAPSYJ { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public Nullable<int> POSICION { get; set; }
        public Nullable<bool> AutorizaSinCargo { get; set; }
    
        public virtual T0085_HHRR_DATOSPERSONALES T0085_HHRR_DATOSPERSONALES { get; set; }
        public virtual T0086_HHRR_POSICIONES T0086_HHRR_POSICIONES { get; set; }
    }
}
