//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0086_HHRR_POSICIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0086_HHRR_POSICIONES()
        {
            this.T0085_PERSONAL = new HashSet<T0085_PERSONAL>();
            this.T0085_HHRR_PERSONAL_BASIC = new HashSet<T0085_HHRR_PERSONAL_BASIC>();
        }
    
        public int IDPOSICION { get; set; }
        public string PosicionDescripcion { get; set; }
        public bool EnConvenio { get; set; }
        public string TipoLiquidacion { get; set; }
        public bool Activo { get; set; }
        public decimal ValorHora { get; set; }
        public decimal ValorMensual { get; set; }
        public decimal Valor { get; set; }
        public decimal AdicionalPresentismo { get; set; }
        public decimal AdicionalBono1 { get; set; }
        public decimal AdicionalBono2 { get; set; }
        public Nullable<System.DateTime> UltimaActualizacion { get; set; }
        public string DescripcionVigencia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0085_PERSONAL> T0085_PERSONAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0085_HHRR_PERSONAL_BASIC> T0085_HHRR_PERSONAL_BASIC { get; set; }
    }
}
