//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0092_HHRR_COMBOASSIGN
    {
        public string Shortname { get; set; }
        public string ComboCode { get; set; }
        public bool Valor { get; set; }
    
        public virtual T0085_HHRR_PERSONAL_BASIC T0085_HHRR_PERSONAL_BASIC { get; set; }
        public virtual T0091_HHRR_COMBOCODE T0091_HHRR_COMBOCODE { get; set; }
    }
}
