//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0090_CLIENTE_MATERIAL
    {
        public int Id { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public string ID_MATERIAL { get; set; }
    }
}
