//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0099_NELS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0099_NELS()
        {
            this.T0099_NELUPDATE = new HashSet<T0099_NELUPDATE>();
        }
    
        public int NEL { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string ClienteDescripcion { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string IngresadoPor { get; set; }
        public string ColorDesarrollo { get; set; }
        public string BaseDesarrollo { get; set; }
        public string EstadoDesarrollo { get; set; }
        public bool EntregoMuestra { get; set; }
        public bool EntregoBase { get; set; }
        public string Presentacion { get; set; }
        public string ComentarioIngreso { get; set; }
        public string CodigoAsignado { get; set; }
        public string CodigoDefinitivo { get; set; }
        public Nullable<System.DateTime> FechaAprobacionCliente { get; set; }
        public string AprobadoPor { get; set; }
        public string LogUser { get; set; }
        public System.DateTime LogFechaIngreso { get; set; }
        public byte[] Foto1 { get; set; }
        public byte[] Foto2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0099_NELUPDATE> T0099_NELUPDATE { get; set; }
    }
}
