//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0098_MUESTRAS
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> IDCLIENTE { get; set; }
        public string CLIENTE_FA { get; set; }
        public string MATERIAL_E { get; set; }
        public string ATENCION { get; set; }
        public string COMENTARIO { get; set; }
        public string LOG_USER { get; set; }
        public Nullable<System.DateTime> LOG_DATE { get; set; }
    }
}
