//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0099_NELUPDATE
    {
        public int NEL { get; set; }
        public int NELSEQ { get; set; }
        public System.DateTime FechaUpdate { get; set; }
        public string UserUpdate { get; set; }
        public string Estado { get; set; }
        public string ComentarioAvance { get; set; }
    
        public virtual T0099_NELS T0099_NELS { get; set; }
    }
}
