//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0091_HHRR_COMBOCODE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0091_HHRR_COMBOCODE()
        {
            this.T0092_HHRR_COMBOASSIGN = new HashSet<T0092_HHRR_COMBOASSIGN>();
        }
    
        public string ComboCode { get; set; }
        public string DescripcionPermiso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0092_HHRR_COMBOASSIGN> T0092_HHRR_COMBOASSIGN { get; set; }
    }
}
