//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0100_MATERIAL_PROVEEDOR
    {
        public int PROVEEDOR { get; set; }
        public string MATERIAL_TECSER { get; set; }
        public string MATERIAL_PROVEEDOR { get; set; }
        public Nullable<System.DateTime> FULTIMACOMPRA { get; set; }
        public Nullable<int> ULTIMACANTIDAD { get; set; }
        public string MONEDAUCOMPRA { get; set; }
        public Nullable<decimal> ULTIMOPRECIO { get; set; }
        public Nullable<int> CALIFICACION { get; set; }
        public string COMENTARIO { get; set; }
        public bool ACTIVO { get; set; }
    }
}
