//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0102_EXCHANGE
    {
        public System.DateTime Fecha { get; set; }
        public Nullable<decimal> CotizacionFactu { get; set; }
        public Nullable<decimal> CotizacionFactuL2 { get; set; }
        public Nullable<decimal> CotizacionCobra { get; set; }
        public string LUSER { get; set; }
        public Nullable<System.DateTime> LDATE { get; set; }
    }
}
