//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0101_MATERIAL_PROVEEDOR_TEMP
    {
        public Nullable<int> IDPROVEEDOR { get; set; }
        public string MATERIAL_TECSER { get; set; }
        public string MATERIAL_PROVEEDOR { get; set; }
        public string MONEDA { get; set; }
        public Nullable<decimal> PRECIOUNITARIO { get; set; }
        public bool ACTIVO { get; set; }
    }
}
