//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0121_CCN2
    {
        public string CCN2 { get; set; }
        public string CCN1 { get; set; }
        public string N2DESC { get; set; }
        public string CC { get; set; }
        public string MONEDA { get; set; }
        public bool ACTIVO { get; set; }
        public string IDRAF { get; set; }
        public string LINK_FORM { get; set; }
        public string TIPO { get; set; }
        public bool DISPO_XREG { get; set; }
    }
}
