//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0137_GL_MAPPING
    {
        public string CUENTA_GEN { get; set; }
        public string CUENTA_DES { get; set; }
        public string DOCUMENTACION { get; set; }
        public string CUENTA_MAP { get; set; }
        public string XMAP_PATH { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
