//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0134_GLL4
    {
        public int IDL4 { get; set; }
        public int IDL3 { get; set; }
        public int IDL2 { get; set; }
        public int IDL1 { get; set; }
        public int IDL0 { get; set; }
        public string IDC { get; set; }
        public string CUENTA_D { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
        public string TSUBMODULO { get; set; }
        public string IDT { get; set; }
        public Nullable<int> IDXN { get; set; }
        public string IDXT { get; set; }
        public string TSUBMODID { get; set; }
        public string Documentacion { get; set; }
        public string CC_Default { get; set; }
        public string Mapeo_1 { get; set; }
        public string Mapeo_2 { get; set; }
        public Nullable<bool> PI { get; set; }
        public string IDC2 { get; set; }
    
        public virtual T0133_GLL3 T0133_GLL3 { get; set; }
    }
}
