//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0139_ResumenCierre
    {
        public string Periodo { get; set; }
        public System.DateTime FechaUpdate { get; set; }
        public decimal SaldoCheques { get; set; }
        public decimal SaldoIcbc { get; set; }
        public decimal SaldoSantander { get; set; }
        public decimal SaldoGalicia { get; set; }
        public decimal KgVendidos { get; set; }
        public decimal KgComprados { get; set; }
        public decimal TotalFacturado { get; set; }
        public decimal TotalComprado { get; set; }
        public decimal TotalGasto { get; set; }
        public decimal TotalPagado { get; set; }
        public string LX { get; set; }
    }
}
