//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0130_GLL0
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0130_GLL0()
        {
            this.T0131_GLL1 = new HashSet<T0131_GLL1>();
        }
    
        public int IDL0 { get; set; }
        public string IDC { get; set; }
        public string CUENTA_D { get; set; }
        public string DOCUMENTACION { get; set; }
        public string IDC2 { get; set; }
        public bool PI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0131_GLL1> T0131_GLL1 { get; set; }
    }
}
