//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0138_PERIODOS
    {
        public string PERIODO { get; set; }
        public string XMES { get; set; }
        public string XYEAR { get; set; }
        public Nullable<bool> PERMITE_FI { get; set; }
        public Nullable<bool> PERMITE_MM { get; set; }
        public Nullable<System.DateTime> FECHA_CIERRE { get; set; }
        public string USER_CIERRE { get; set; }
        public Nullable<int> ZMES { get; set; }
        public Nullable<System.DateTime> FECHA_OPEN { get; set; }
        public Nullable<bool> REOPEN { get; set; }
    }
}
