//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0139_GL_CIERRE_TEMPORAL
    {
        public int ID { get; set; }
        public string GL { get; set; }
        public string GL_DESC { get; set; }
        public string GL_L { get; set; }
        public Nullable<decimal> SALDO { get; set; }
        public string XMES { get; set; }
        public string XYEAR { get; set; }
        public string XPERIODO { get; set; }
        public string LOG_U_CIERRE { get; set; }
        public Nullable<System.DateTime> LOG_D_CIERRE { get; set; }
        public string LOG_U_MODI { get; set; }
        public Nullable<System.DateTime> LOG_D_MODI { get; set; }
    }
}
