//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0136_GLTREE
    {
        public int ID { get; set; }
        public string L0 { get; set; }
        public string L1 { get; set; }
        public string L2 { get; set; }
        public string L3 { get; set; }
        public string L4 { get; set; }
        public Nullable<decimal> D0 { get; set; }
        public Nullable<decimal> D1 { get; set; }
        public Nullable<decimal> D2 { get; set; }
        public Nullable<decimal> D3 { get; set; }
        public Nullable<decimal> D4 { get; set; }
        public Nullable<decimal> H0 { get; set; }
        public Nullable<decimal> H1 { get; set; }
        public Nullable<decimal> H2 { get; set; }
        public Nullable<decimal> H3 { get; set; }
        public Nullable<decimal> H4 { get; set; }
        public Nullable<decimal> S0 { get; set; }
        public Nullable<decimal> S1 { get; set; }
        public Nullable<decimal> S2 { get; set; }
        public Nullable<decimal> S3 { get; set; }
        public Nullable<decimal> S4 { get; set; }
        public string T0 { get; set; }
        public string T1 { get; set; }
        public string T2 { get; set; }
        public string T3 { get; set; }
        public string T4 { get; set; }
        public Nullable<decimal> DX { get; set; }
        public Nullable<decimal> HX { get; set; }
        public Nullable<decimal> SX { get; set; }
        public Nullable<int> LX { get; set; }
        public Nullable<decimal> DACC { get; set; }
        public Nullable<decimal> HACC { get; set; }
        public Nullable<decimal> SACC { get; set; }
        public string TipoLX { get; set; }
        public Nullable<int> TreeLevel { get; set; }
        public string GLAccount { get; set; }
        public string GLDescripcion { get; set; }
    }
}
