//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0140_MargenOperacion
    {
        public int IdRemito { get; set; }
        public int IdItem { get; set; }
        public int IdCliente { get; set; }
        public string ClienteRs { get; set; }
        public string RemitoNum { get; set; }
        public Nullable<System.DateTime> FechaRemito { get; set; }
        public Nullable<System.DateTime> FechaFactura { get; set; }
        public Nullable<decimal> TCFactura { get; set; }
        public string FacturaNum { get; set; }
        public string Material { get; set; }
        public string MonCosto { get; set; }
        public string TipoLX { get; set; }
        public decimal PrecioU1 { get; set; }
        public decimal PrecioU2 { get; set; }
        public decimal PrecioU { get; set; }
        public decimal Cantidad { get; set; }
        public decimal PrecioTotal { get; set; }
        public decimal CostoMfg { get; set; }
        public decimal CostoStadistico { get; set; }
        public decimal CostoUAdd { get; set; }
        public decimal CostoTotalAdd { get; set; }
        public decimal CostoTotal { get; set; }
        public decimal MargenOperacionVenta { get; set; }
        public Nullable<decimal> MargenOperaconVentaUnitario { get; set; }
        public decimal PorcentajeCobrado { get; set; }
        public decimal PrecioCobradoTotal { get; set; }
        public decimal MargenOperacionFinal { get; set; }
        public Nullable<int> IdFactura { get; set; }
        public Nullable<System.Guid> CRVersion { get; set; }
        public Nullable<System.DateTime> CostMapDate { get; set; }
        public Nullable<int> DiasReciboPago { get; set; }
        public Nullable<int> DiasAcreditacionValores { get; set; }
        public int IdClienteEntrega { get; set; }
        public string Vendedor { get; set; }
    }
}
