//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0158_CHRTRACKER
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Usuario { get; set; }
        public int ChequeId { get; set; }
        public string ChequeBco { get; set; }
        public decimal ChequeImporte { get; set; }
        public string Origen { get; set; }
        public string AccionCheque { get; set; }
        public string AccionCliente { get; set; }
        public int AsientoChr { get; set; }
        public string DocumentoRef { get; set; }
        public string Motivo { get; set; }
        public string CuentaOrigen { get; set; }
        public string CuentaDestino { get; set; }
        public string NDNumero { get; set; }
        public Nullable<int> IDND { get; set; }
    
        public virtual T0154_CHEQUES T0154_CHEQUES { get; set; }
    }
}
