//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0156_CHEQUE_RECH
    {
        public int IDCHEQUE { get; set; }
        public string NUMERO { get; set; }
        public string BANCO_SN { get; set; }
        public decimal IMPORTE { get; set; }
        public int IDCLIENTE { get; set; }
        public string CLIENTERS { get; set; }
        public System.DateTime FECHA_CH { get; set; }
        public Nullable<System.DateTime> FECHA_RE { get; set; }
        public string MOTIVO_RE { get; set; }
        public string NC_NUM { get; set; }
        public Nullable<int> AS_RECH { get; set; }
        public Nullable<int> AS_NC { get; set; }
        public string TIPO { get; set; }
        public string LOG_USER { get; set; }
        public Nullable<System.DateTime> LOG_DATE { get; set; }
        public Nullable<System.DateTime> FechaEntregado { get; set; }
        public bool ChequeEntregado { get; set; }
        public string EntregadoPor { get; set; }
        public int IdNCT400 { get; set; }
        public decimal GastosOrigen { get; set; }
        public decimal IVAGastosOrigen { get; set; }
        public string OrigenRechazo { get; set; }
    }
}
