//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0151_MONEDAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0151_MONEDAS()
        {
            this.T0060_OCOMPRA_H = new HashSet<T0060_OCOMPRA_H>();
            this.T0150_CUENTAS = new HashSet<T0150_CUENTAS>();
        }
    
        public string IdMoneda { get; set; }
        public string MonedaDescripcion { get; set; }
        public bool MonedaDefault { get; set; }
        public Nullable<decimal> ConversionDefault { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0060_OCOMPRA_H> T0060_OCOMPRA_H { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0150_CUENTAS> T0150_CUENTAS { get; set; }
    }
}
