//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0159_CHEQUES_EMITIDOS
    {
        public int IDRecord { get; set; }
        public string NumeroCheque { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public System.DateTime FechaAcreditacion { get; set; }
        public bool PendienteAcreditacion { get; set; }
        public string LogEmisor { get; set; }
        public System.DateTime LogFechaEmison { get; set; }
        public decimal ImporteCheque { get; set; }
        public string BancoChequeShort { get; set; }
        public int OrdenPagoNumero { get; set; }
        public int Proveedor { get; set; }
        public string Status { get; set; }
        public bool ECheque { get; set; }
        public Nullable<System.DateTime> FechaAcreditacionReal { get; set; }
        public string LX { get; set; }
        public int IdRegister { get; set; }
        public Nullable<decimal> NasEmision { get; set; }
        public Nullable<decimal> NasAcreditacion { get; set; }
    }
}
