//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0150_CUENTAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0150_CUENTAS()
        {
            this.T0206_COBRANZA_I = new HashSet<T0206_COBRANZA_I>();
            this.T0212_OP_ITEM = new HashSet<T0212_OP_ITEM>();
        }
    
        public string ID_CUENTA { get; set; }
        public string CUENTA_DESC { get; set; }
        public string CUENTA_TIPO { get; set; }
        public string CUENTA_MONEDA { get; set; }
        public string CUENTA_NUMERO { get; set; }
        public string CUENTA_CBU { get; set; }
        public string GLMAP { get; set; }
        public bool DisponibleOP { get; set; }
        public bool DisponibleCobranza { get; set; }
        public bool DisponibleConta1 { get; set; }
        public bool DisponibleContar { get; set; }
        public bool DisponibleSYJ { get; set; }
        public bool DisponibleREG { get; set; }
        public string Descripcion2 { get; set; }
        public bool TRANSFERENCIA { get; set; }
        public bool EmiteCheque { get; set; }
    
        public virtual T0151_MONEDAS T0151_MONEDAS { get; set; }
        public virtual T0155_SALDOS T0155_SALDOS { get; set; }
        public virtual T0155_SALDOS T0155_SALDOS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0206_COBRANZA_I> T0206_COBRANZA_I { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0212_OP_ITEM> T0212_OP_ITEM { get; set; }
    }
}
