//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0157_INFOCUITCHEQUE
    {
        public string CUIT { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> NCHEQUESRECIBIDOS { get; set; }
        public Nullable<int> NCHEQUESRECHAZADOS { get; set; }
        public Nullable<int> BANCO { get; set; }
        public string NUMEROCUENTA { get; set; }
    }
}
