//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0160_BANCOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0160_BANCOS()
        {
            this.T0154_CHEQUES = new HashSet<T0154_CHEQUES>();
        }
    
        public string ID_BANCO { get; set; }
        public string BANCO { get; set; }
        public string BANCO_DESC { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
        public string BCO_SHORTDESC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0154_CHEQUES> T0154_CHEQUES { get; set; }
    }
}
