//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0170BloqueoDocumentos
    {
        public int IdBloqueo { get; set; }
        public string TdocBloqueo { get; set; }
        public int IdDocBloqueo { get; set; }
        public string NumeroDocBloqueo { get; set; }
        public System.DateTime FechaBloqueo { get; set; }
        public string UsuarioBloqueo { get; set; }
        public string MotivoBloqueo { get; set; }
        public string ComentarioAdicionalBloqueo { get; set; }
        public string UsuarioDesbloqueo { get; set; }
        public Nullable<System.DateTime> FechaDesbloqueo { get; set; }
        public string ComentarioDesbloqueo { get; set; }
        public bool BloqueoActivo { get; set; }
        public string RazonSocial { get; set; }
        public int IdCliente { get; set; }
        public System.DateTime LogDate { get; set; }
        public string LogUserComputer { get; set; }
    }
}
