//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0205_COBRANZA_H
    {
        public int IDCOB { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string NRECIBO { get; set; }
        public string NRECIPROVI { get; set; }
        public string CUENTA { get; set; }
        public string MON { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal Monto { get; set; }
        public string ReciboDesc { get; set; }
        public string LogUser { get; set; }
        public System.DateTime LogDate { get; set; }
        public bool CCK { get; set; }
        public bool IMPRESO { get; set; }
        public decimal TC { get; set; }
        public bool DOC_CANCELADO { get; set; }
        public bool DOC_DESIMPUTADO { get; set; }
        public Nullable<int> NASIENTO_R { get; set; }
        public Nullable<int> NASIENTO_C { get; set; }
        public Nullable<int> DIAS_PP { get; set; }
        public Nullable<int> NASIENTO { get; set; }
        public string NRECIBOOFI { get; set; }
        public bool ENVIAREMAIL { get; set; }
        public string EMAIL { get; set; }
        public bool ENVIADO { get; set; }
        public string EMAILMENSAJE { get; set; }
    
        public virtual T0006_MCLIENTES T0006_MCLIENTES { get; set; }
    }
}
