//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0203_CTACTE_PROV_IMPU
    {
        public int CTACTE1 { get; set; }
        public int CTACTE2 { get; set; }
        public Nullable<decimal> MONTO_IMPU { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string LogUser { get; set; }
        public string TCODE { get; set; }
        public string GLPAGO { get; set; }
        public Nullable<int> NAS_PAGO { get; set; }
        public Nullable<int> IDPROV { get; set; }
        public string NUMDOC { get; set; }
        public string TDOC { get; set; }
    
        public virtual T0203_CTACTE_PROV T0203_CTACTE_PROV { get; set; }
    }
}
