//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0201_CTACTE
    {
        public int IDCTACTE { get; set; }
        public string TDOC { get; set; }
        public Nullable<int> IDDOC { get; set; }
        public string DOC_INTERNO { get; set; }
        public string NUMDOC { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> ZTERM { get; set; }
        public int IDCLI { get; set; }
        public string MONEDA { get; set; }
        public Nullable<decimal> TC { get; set; }
        public decimal IMPORTE_ORI { get; set; }
        public decimal IMPORTE_ARS { get; set; }
        public decimal SALDOFACTURA { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string LogUsuario { get; set; }
        public string TIPO { get; set; }
        public string CK { get; set; }
        public Nullable<decimal> CTACTE { get; set; }
        public Nullable<int> IDT1 { get; set; }
        public Nullable<int> IDT2 { get; set; }
        public Nullable<int> DiasPImputacion { get; set; }
        public Nullable<int> DiasPAcreditacion { get; set; }
    
        public virtual T0006_MCLIENTES T0006_MCLIENTES { get; set; }
    }
}
