//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0208_COB_NO_APLICADA
    {
        public int ID { get; set; }
        public Nullable<int> CLIENTE { get; set; }
        public Nullable<int> IDRECIBO { get; set; }
        public Nullable<int> IDNCD { get; set; }
        public string NRECIBO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string MONEDA { get; set; }
        public Nullable<decimal> MONTO { get; set; }
        public string TIPOCUENTA { get; set; }
        public string TIPODOC { get; set; }
        public Nullable<int> IDCTACTE { get; set; }
    
        public virtual T0006_MCLIENTES T0006_MCLIENTES { get; set; }
    }
}
