//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0203_CTACTE_PROV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0203_CTACTE_PROV()
        {
            this.T0203_CTACTE_PROV_IMPU = new HashSet<T0203_CTACTE_PROV_IMPU>();
        }
    
        public int IDCTACTE { get; set; }
        public string TDOC { get; set; }
        public string DOC_INTERNO { get; set; }
        public string NUMDOC { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> ZTERM { get; set; }
        public int IDPROV { get; set; }
        public string MONEDA { get; set; }
        public Nullable<decimal> TC { get; set; }
        public Nullable<decimal> IMPORTE_ORI { get; set; }
        public Nullable<decimal> IMPORTE_ARS { get; set; }
        public Nullable<decimal> SALDOFACTURA { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string LogUsuario { get; set; }
        public string TIPO { get; set; }
        public Nullable<bool> ZOP { get; set; }
        public Nullable<int> IdFacturaX { get; set; }
        public Nullable<int> IDDOC { get; set; }
    
        public virtual T0005_MPROVEEDORES T0005_MPROVEEDORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0203_CTACTE_PROV_IMPU> T0203_CTACTE_PROV_IMPU { get; set; }
    }
}
