//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0210_OP_H
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0210_OP_H()
        {
            this.T0212_OP_ITEM = new HashSet<T0212_OP_ITEM>();
            this.T0213_OP_FACT = new HashSet<T0213_OP_FACT>();
        }
    
        public int IDOP { get; set; }
        public Nullable<System.DateTime> OPFECHA { get; set; }
        public int PROV_ID { get; set; }
        public string PROV_RS { get; set; }
        public string PROV_TAXID { get; set; }
        public string PROV_TAXNUM { get; set; }
        public string PROV_CUIT { get; set; }
        public string MON_OP { get; set; }
        public Nullable<decimal> IMP_OP { get; set; }
        public bool OP_TEMP { get; set; }
        public string OP_STATUS { get; set; }
        public string TIPO { get; set; }
        public string OP_COM { get; set; }
        public string LOG_USER { get; set; }
        public Nullable<System.DateTime> LOG_DATE { get; set; }
        public string Periodo { get; set; }
        public Nullable<decimal> ImporteValores { get; set; }
        public Nullable<decimal> ImporteIVA { get; set; }
        public Nullable<decimal> ImporteRetIVA { get; set; }
        public Nullable<decimal> ImporteRetIIBB { get; set; }
        public Nullable<decimal> ImporteCreditos { get; set; }
        public Nullable<decimal> ImporteRetGS { get; set; }
        public Nullable<decimal> TC { get; set; }
        public Nullable<decimal> SaldoSinImputar { get; set; }
        public Nullable<int> NAS { get; set; }
        public Nullable<decimal> BaseCalculoPagoRetGS { get; set; }
        public Nullable<int> DiasPPFacturas { get; set; }
        public Nullable<int> DiasPPItemsPago { get; set; }
    
        public virtual T0005_MPROVEEDORES T0005_MPROVEEDORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0212_OP_ITEM> T0212_OP_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0213_OP_FACT> T0213_OP_FACT { get; set; }
    }
}
