//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0213_OrdenPagoRetenciones
    {
        public int IdOP { get; set; }
        public int IdItemRetencion { get; set; }
        public string RetencionTipo { get; set; }
        public decimal BaseImponibleCalculo { get; set; }
        public string GL { get; set; }
        public decimal Alicuota { get; set; }
        public decimal ImporteRetencion { get; set; }
    
        public virtual T0210_OrdenPagoHeader T0210_OrdenPagoHeader { get; set; }
    }
}
