//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0231_GescoDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0231_GescoDetail()
        {
            this.T0232_GescoPagosListos = new HashSet<T0232_GescoPagosListos>();
        }
    
        public int IdCliente { get; set; }
        public int IdRecord { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string ContactoCliente { get; set; }
        public string TipoMensajeECI { get; set; }
        public int MotivoPrincipalContacto { get; set; }
        public string MedioContacto { get; set; }
        public string MensajeIO { get; set; }
        public bool CompromisoPago { get; set; }
        public Nullable<System.DateTime> FechaCompromisoPago { get; set; }
        public bool CanceloPago { get; set; }
        public string CanceloMotivo { get; set; }
        public bool CuentaConciliadaOK { get; set; }
        public bool CuentaConDiferencias { get; set; }
        public bool AgendoProximaLlamada { get; set; }
        public Nullable<System.DateTime> ProximaLlamadaFecha { get; set; }
        public string LogUser { get; set; }
        public System.DateTime LogDate { get; set; }
        public Nullable<System.DateTime> PagoIngresado { get; set; }
        public Nullable<int> PagoIngresadoId { get; set; }
        public bool FechaPagoModificada { get; set; }
    
        public virtual T0230_GescoHeader T0230_GescoHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0232_GescoPagosListos> T0232_GescoPagosListos { get; set; }
    }
}
