//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0232_GescoPagosListos
    {
        public int idCliente { get; set; }
        public int idRecord { get; set; }
        public System.DateTime FechaPago { get; set; }
        public bool PagoCancelado { get; set; }
        public string MensajeCobrador { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Direccion2 { get; set; }
        public string DiasHorarios { get; set; }
        public string LogUser { get; set; }
        public System.DateTime LogDate { get; set; }
        public string CobradorAsignado { get; set; }
        public Nullable<System.DateTime> RetiroProgramado { get; set; }
        public Nullable<bool> FechaModificada { get; set; }
        public int IdRecordPagoListo { get; set; }
        public Nullable<int> IdRecordLastUpdate { get; set; }
    
        public virtual T0231_GescoDetail T0231_GescoDetail { get; set; }
    }
}
