//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0290_COMPFACT_T
    {
        public int IDCTACTE { get; set; }
        public Nullable<decimal> SALDOFACT { get; set; }
        public Nullable<decimal> MONTO { get; set; }
        public string TIPO { get; set; }
        public string NUMDOC { get; set; }
    }
}
