//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0300_NCD_H
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0300_NCD_H()
        {
            this.T0301_NCD_I = new HashSet<T0301_NCD_I>();
        }
    
        public int IDH { get; set; }
        public string TDOC { get; set; }
        public string NDOC { get; set; }
        public string LX { get; set; }
        public string MON { get; set; }
        public int IdCliente { get; set; }
        public string RazonSocial { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal TC { get; set; }
        public decimal ImporteARS { get; set; }
        public decimal ImporteUSD { get; set; }
        public string COMENTARIO { get; set; }
        public Nullable<int> ASIENTO { get; set; }
        public string LOGUSER { get; set; }
        public System.DateTime LOGDATE { get; set; }
        public bool TEMP { get; set; }
        public Nullable<int> idFacturaT0400 { get; set; }
        public Nullable<int> idCtaCte { get; set; }
        public Nullable<decimal> idFacturaX { get; set; }
        public Nullable<int> idFacturaAsociada { get; set; }
        public Nullable<System.DateTime> PeriodoAjusteDesde { get; set; }
        public Nullable<System.DateTime> PeriodoAjusteHasta { get; set; }
        public string Motivo { get; set; }
        public Nullable<int> IdMotivoAsociado { get; set; }
        public string AutorizadoPor { get; set; }
        public bool OperacionRevisada { get; set; }
    
        public virtual T0006_MCLIENTES T0006_MCLIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0301_NCD_I> T0301_NCD_I { get; set; }
    }
}
