//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0311_NCDP_I
    {
        public int IDH { get; set; }
        public int IDITEM { get; set; }
        public string TDOC { get; set; }
        public string NDOC { get; set; }
        public Nullable<decimal> CANT { get; set; }
        public string ITEM { get; set; }
        public string DESC { get; set; }
        public string MON { get; set; }
        public Nullable<decimal> PUNITARIO { get; set; }
        public Nullable<decimal> PTOTAL { get; set; }
        public Nullable<decimal> PTOTAL_ARS { get; set; }
        public Nullable<bool> IVA21 { get; set; }
        public Nullable<decimal> PIVA { get; set; }
        public Nullable<decimal> PTOTAL_ARS_NETO { get; set; }
        public Nullable<bool> TEMP { get; set; }
        public string GL { get; set; }
        public Nullable<bool> CHR { get; set; }
        public Nullable<int> IDCH { get; set; }
    
        public virtual T0310_NCDP_H T0310_NCDP_H { get; set; }
    }
}
