//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0310_NCDP_H
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0310_NCDP_H()
        {
            this.T0311_NCDP_I = new HashSet<T0311_NCDP_I>();
        }
    
        public int IDH { get; set; }
        public string TDOC { get; set; }
        public string NDOC { get; set; }
        public string TIPO { get; set; }
        public string MON { get; set; }
        public Nullable<bool> APLICA { get; set; }
        public string APLICA_TDOC { get; set; }
        public string APLICA_DOC { get; set; }
        public Nullable<int> CLINUM { get; set; }
        public string CLITXT { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<decimal> TC { get; set; }
        public Nullable<decimal> TOTAL_USD_BRUTO { get; set; }
        public Nullable<decimal> TOTAL_ARS_BRUTO { get; set; }
        public Nullable<decimal> TOTAL_IVA { get; set; }
        public Nullable<decimal> TOTAL_IMPO { get; set; }
        public Nullable<decimal> TOTAL_ARS_NETO { get; set; }
        public Nullable<decimal> TOTAL_USD_NETO { get; set; }
        public string COMENTARIO { get; set; }
        public Nullable<int> ASIENTO { get; set; }
        public string LOGUSER { get; set; }
        public Nullable<System.DateTime> LOGDATE { get; set; }
        public Nullable<bool> TEMP { get; set; }
        public Nullable<int> IdCtaCte { get; set; }
        public Nullable<int> IdT0403 { get; set; }
        public Nullable<decimal> TotalPercIIBB { get; set; }
        public Nullable<decimal> TotalPercIVA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0311_NCDP_I> T0311_NCDP_I { get; set; }
    }
}
