//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0360_RTN
    {
        public int IDX { get; set; }
        public System.DateTime FECHA { get; set; }
        public int IDCLI { get; set; }
        public string CLIENTE { get; set; }
        public string TIPO_MOV { get; set; }
        public string MOTIVO { get; set; }
        public string MATERIAL { get; set; }
        public string LOTE { get; set; }
        public decimal KG { get; set; }
        public string UBICACION { get; set; }
        public string RECIBIO { get; set; }
        public string COMENTARIO { get; set; }
        public string COMERCIAL { get; set; }
        public Nullable<int> NASIENTO { get; set; }
        public Nullable<int> NID40 { get; set; }
        public string LogCreadoPor { get; set; }
        public System.DateTime LogCreadoEn { get; set; }
        public string AprobadoPor { get; set; }
        public string NumeroNC { get; set; }
        public Nullable<decimal> KgNC { get; set; }
        public string ObservacionLaboratorio { get; set; }
    }
}
