//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0405_FACTURAS_RETENCIONES
    {
        public string ProveedorRazonSocial { get; set; }
        public string CUIT { get; set; }
        public string PeriodoOP { get; set; }
        public string TipoDocumento { get; set; }
        public string NumeroFactura { get; set; }
        public string RetGsConcepto { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public int NumeroOP { get; set; }
        public Nullable<System.DateTime> FechaOP { get; set; }
        public Nullable<int> IDFacturaProveedor { get; set; }
        public Nullable<decimal> BaseImponibleDocumento { get; set; }
        public Nullable<decimal> RetGSBase { get; set; }
        public Nullable<decimal> RetGSBaseCalculo { get; set; }
        public Nullable<decimal> RetGSAlicuota { get; set; }
        public Nullable<decimal> RetGSARetener { get; set; }
        public Nullable<decimal> RetIIBBAlicuota { get; set; }
        public Nullable<decimal> RetIIBBARetener { get; set; }
        public string RetGSCertificado { get; set; }
        public string RetIIBBCertificado { get; set; }
        public string StatusRetencion { get; set; }
        public Nullable<bool> Modificado { get; set; }
    }
}
