//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0402_FACTURA_PERCEP
    {
        public int IdFactura { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string NumFactura { get; set; }
        public Nullable<System.DateTime> FechaFactura { get; set; }
        public string IIBB_Perc_TXT { get; set; }
        public Nullable<decimal> IIBB_Perc_Porc { get; set; }
        public Nullable<decimal> IIBB_Perc_ARS { get; set; }
        public Nullable<decimal> IIBB_Perc_ARS_Saldo { get; set; }
        public string IIBB_Perc_DocPago { get; set; }
        public Nullable<System.DateTime> IIBB_Perc_FechaPago { get; set; }
        public Nullable<int> IDCtaCte { get; set; }
        public Nullable<System.DateTime> FechaImputacion { get; set; }
        public Nullable<bool> Informado { get; set; }
    }
}
