//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0404_VENDOR_FACT_I
    {
        public int IDINT { get; set; }
        public int IDIT { get; set; }
        public string IDITEM { get; set; }
        public string ITEM_DESC { get; set; }
        public Nullable<decimal> TC { get; set; }
        public string MONEDA { get; set; }
        public Nullable<decimal> PUNIT { get; set; }
        public Nullable<decimal> PUNIT_USD { get; set; }
        public Nullable<decimal> PUNIT_ARS { get; set; }
        public Nullable<decimal> PTOTAL_ARS { get; set; }
        public Nullable<decimal> PTOTAL_USD { get; set; }
        public Nullable<decimal> BRUTO { get; set; }
        public Nullable<decimal> DTO { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
        public Nullable<decimal> IVA10 { get; set; }
        public Nullable<decimal> IVA21 { get; set; }
        public Nullable<decimal> RETIVA { get; set; }
        public Nullable<decimal> RETIIBB { get; set; }
        public Nullable<decimal> IMPINT { get; set; }
        public Nullable<decimal> IMPOTR { get; set; }
        public Nullable<decimal> NETO { get; set; }
        public string GL { get; set; }
        public Nullable<decimal> CANT { get; set; }
        public Nullable<bool> IVA { get; set; }
        public Nullable<int> IDCHE { get; set; }
        public string MonedaItemProveedor { get; set; }
        public Nullable<int> Id063 { get; set; }
    
        public virtual T0403_VENDOR_FACT_H T0403_VENDOR_FACT_H { get; set; }
    }
}
