//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0406_RendicionFF_H
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0406_RendicionFF_H()
        {
            this.T0407_RendicionFF_I = new HashSet<T0407_RendicionFF_I>();
        }
    
        public int idRendicion { get; set; }
        public int idVendor { get; set; }
        public string razonSocial { get; set; }
        public string tipoLx { get; set; }
        public string tipoDocumento { get; set; }
        public string numeroDocumento { get; set; }
        public System.DateTime fechaDocumento { get; set; }
        public string moneda { get; set; }
        public decimal importeBruto { get; set; }
        public decimal descuento { get; set; }
        public decimal subtotal { get; set; }
        public decimal baseImponible { get; set; }
        public decimal iva10 { get; set; }
        public decimal iva21 { get; set; }
        public decimal iva27 { get; set; }
        public decimal alicPercIIBB { get; set; }
        public decimal alicPercIVA { get; set; }
        public decimal impPercIIBB { get; set; }
        public decimal impPercIVA { get; set; }
        public decimal impMunicipales { get; set; }
        public decimal impProvinciales { get; set; }
        public decimal impInternos { get; set; }
        public decimal otrosImpuestos { get; set; }
        public decimal concNoGravados { get; set; }
        public Nullable<decimal> ImporteNetoFinal { get; set; }
        public string StatusRendicion { get; set; }
        public string gastoAutorizadoPor { get; set; }
        public string rendicionAprobadaPor { get; set; }
        public string GLAP { get; set; }
        public string RendicionCuentaGL { get; set; }
        public Nullable<int> numeroAsiento { get; set; }
        public Nullable<int> id403 { get; set; }
        public string LogUser { get; set; }
        public System.DateTime LogFecha { get; set; }
        public Nullable<int> idCtaCte { get; set; }
        public string Comentario { get; set; }
        public string RendicionCuentaGLId { get; set; }
    
        public virtual T0005_MPROVEEDORES T0005_MPROVEEDORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0407_RendicionFF_I> T0407_RendicionFF_I { get; set; }
    }
}
