//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0400_FACTURA_H
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0400_FACTURA_H()
        {
            this.T0401_FACTURA_I = new HashSet<T0401_FACTURA_I>();
        }
    
        public Nullable<int> IDFACTURAX { get; set; }
        public int IDFACTURA { get; set; }
        public string PV_AFIP { get; set; }
        public string ND_AFIP { get; set; }
        public string NumeroDoc { get; set; }
        public string TIPO_DOC { get; set; }
        public string TIPOFACT { get; set; }
        public System.DateTime FECHA { get; set; }
        public int Cliente { get; set; }
        public string RAZONSOC { get; set; }
        public string CUIT { get; set; }
        public string DIRECCION_FAC { get; set; }
        public string LOC_FAC { get; set; }
        public string StatusFactura { get; set; }
        public bool Impreso { get; set; }
        public string ZTERM { get; set; }
        public string FacturaMoneda { get; set; }
        public decimal TC { get; set; }
        public decimal TotalFacturaB { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public decimal TotalImpo { get; set; }
        public decimal TotalIVA21 { get; set; }
        public decimal TotalIIBB { get; set; }
        public decimal TotalFacturaN { get; set; }
        public string CAE { get; set; }
        public Nullable<System.DateTime> CAE_VTO { get; set; }
        public string UserLog { get; set; }
        public System.DateTime FechaLog { get; set; }
        public Nullable<int> IDRemito { get; set; }
        public string Remito { get; set; }
        public Nullable<int> NAS { get; set; }
        public Nullable<decimal> IIBB_PORC { get; set; }
        public string IIBB_TXT { get; set; }
        public Nullable<decimal> NASX1X2 { get; set; }
        public string OR { get; set; }
        public Nullable<bool> RE { get; set; }
        public string ID { get; set; }
        public Nullable<int> IdCtaCte { get; set; }
        public Nullable<decimal> DescuentoPorc { get; set; }
        public Nullable<int> FsrId { get; set; }
        public bool Anulado { get; set; }
        public string GLAR { get; set; }
        public bool ImpactaVentas { get; set; }
        public Nullable<int> IdNCD { get; set; }
        public string Observacion { get; set; }
        public string Tax2Descripcion { get; set; }
        public decimal Tax2Importe { get; set; }
        public decimal Tax2Alicuota { get; set; }
    
        public virtual T0006_MCLIENTES T0006_MCLIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0401_FACTURA_I> T0401_FACTURA_I { get; set; }
    }
}
