//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0403_VENDOR_FACT_H
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0403_VENDOR_FACT_H()
        {
            this.T0404_VENDOR_FACT_I = new HashSet<T0404_VENDOR_FACT_I>();
        }
    
        public int IDINT { get; set; }
        public int IDPROV { get; set; }
        public string PROVRS { get; set; }
        public string PRTAX1 { get; set; }
        public System.DateTime FECHA { get; set; }
        public string MON { get; set; }
        public string TFACTURA { get; set; }
        public string NFACTURA { get; set; }
        public decimal IMPORI { get; set; }
        public decimal TC { get; set; }
        public string TIPO { get; set; }
        public decimal BRUTO { get; set; }
        public decimal DTO { get; set; }
        public decimal SUBTOTAL { get; set; }
        public decimal BaseImponible { get; set; }
        public decimal IVA10 { get; set; }
        public decimal IVA21 { get; set; }
        public decimal IVA27 { get; set; }
        public decimal TOTALIVA { get; set; }
        public decimal PerIVA { get; set; }
        public Nullable<decimal> PerIVA_Alicuota { get; set; }
        public decimal PerIIBB { get; set; }
        public Nullable<decimal> PerIIBB_Alicuota { get; set; }
        public string PerIIBB_TXT { get; set; }
        public decimal ImpuestoMunicipal { get; set; }
        public decimal ImpuestoProvincial { get; set; }
        public decimal IMPINT { get; set; }
        public decimal IMPOTR { get; set; }
        public string LOGUSER { get; set; }
        public Nullable<System.DateTime> LOGDATE { get; set; }
        public Nullable<int> NASIENTO { get; set; }
        public string TCODE { get; set; }
        public Nullable<int> IDCTACTE { get; set; }
        public string GLAP { get; set; }
        public Nullable<decimal> CANTKG { get; set; }
        public string OBSERVACION { get; set; }
        public Nullable<decimal> IdFacturaX { get; set; }
        public Nullable<decimal> PerGA_Alicuota { get; set; }
        public decimal PerGS { get; set; }
        public Nullable<decimal> SALDOIMPAGO { get; set; }
        public decimal ConceptosNoGravados { get; set; }
        public decimal TotalImpuestosVarios { get; set; }
        public decimal NETO { get; set; }
        public string StatusDocumento { get; set; }
        public decimal RedondeoFinal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0404_VENDOR_FACT_I> T0404_VENDOR_FACT_I { get; set; }
    }
}
