//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0500_ERROR_MOV_STK
    {
        public int IDErrorStk { get; set; }
        public string Material { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Batch { get; set; }
        public string Operacion { get; set; }
        public Nullable<double> StockAnterior { get; set; }
        public Nullable<double> StockNuevo { get; set; }
        public string Descripcion { get; set; }
        public string TipoDocumento { get; set; }
        public string Documento { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Usuario { get; set; }
    }
}
