//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0510_ADELANTOS_H
    {
        public Nullable<int> ADELANTOID { get; set; }
        public string EMPL { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string MOTIVO { get; set; }
        public string PROYECTO { get; set; }
        public string MON { get; set; }
        public Nullable<decimal> IMPORTE_O { get; set; }
        public Nullable<float> TC { get; set; }
        public Nullable<decimal> IMPORTE_ARS { get; set; }
        public Nullable<decimal> ARENDIR_O { get; set; }
        public string ASIENTO_GEN { get; set; }
        public Nullable<System.DateTime> LOG_DATE { get; set; }
        public string LOG_USER { get; set; }
        public bool CKFIN { get; set; }
        public string GLEMPL { get; set; }
        public Nullable<decimal> RENDIR_TMP { get; set; }
        public string DEVOLUCION_METODO { get; set; }
        public string GLGS { get; set; }
        public string GLAP { get; set; }
    }
}
