//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0519_SYJHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0519_SYJHeader()
        {
            this.T0520_SYJItems = new HashSet<T0520_SYJItems>();
        }
    
        public int idH { get; set; }
        public System.DateTime FechaConta { get; set; }
        public string Descripcion { get; set; }
        public string Lx { get; set; }
        public string Periodo { get; set; }
        public string Moneda { get; set; }
        public decimal ImporteTotal { get; set; }
        public decimal ImportePagado { get; set; }
        public string LogUser { get; set; }
        public System.DateTime LogDate { get; set; }
        public bool Aprobado { get; set; }
        public string AprobadoPor { get; set; }
        public Nullable<System.DateTime> AprobadoEn { get; set; }
        public string Asiento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0520_SYJItems> T0520_SYJItems { get; set; }
    }
}
