//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0518_ConceptosHR
    {
        public string IdConceptoHR { get; set; }
        public string Concepto { get; set; }
        public bool DisponibleQuincena { get; set; }
        public bool DisponibleMensual { get; set; }
        public string GL1 { get; set; }
        public string GL2 { get; set; }
        public bool VisbleUsuario { get; set; }
    }
}
