//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0511_ADELANTOS_I
    {
        public Nullable<int> ADELANTOID { get; set; }
        public Nullable<int> ITEM { get; set; }
        public string CUENTA { get; set; }
        public Nullable<decimal> IMPORTE_ORI { get; set; }
        public Nullable<decimal> IMPORTE_ARS { get; set; }
        public string GLCUENTA { get; set; }
        public bool CH { get; set; }
        public Nullable<int> CHID { get; set; }
        public string CHBCO { get; set; }
    }
}
