//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0551_HHRR_SYJ_Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0551_HHRR_SYJ_Items()
        {
            this.T0552_HHRR_SYJ_Payments = new HashSet<T0552_HHRR_SYJ_Payments>();
        }
    
        public int IdItem { get; set; }
        public int IdHead { get; set; }
        public string Shortname { get; set; }
        public string Concepto { get; set; }
        public string Observacion { get; set; }
        public string ModoLiquidacion { get; set; }
        public string LX { get; set; }
        public decimal BasicoUnit { get; set; }
        public decimal Imponible { get; set; }
        public decimal NoImponible { get; set; }
        public decimal Descuentos { get; set; }
        public decimal Descuentos2 { get; set; }
        public decimal Adicional2 { get; set; }
        public decimal NetoPagar { get; set; }
        public decimal Adeudado { get; set; }
        public Nullable<int> NAS { get; set; }
        public string LogUserUpdate { get; set; }
        public Nullable<System.DateTime> LogDateUpdate { get; set; }
        public System.DateTime LogDateCreado { get; set; }
        public string LogUserCreado { get; set; }
        public decimal Cantidad { get; set; }
    
        public virtual T0085_HHRR_PERSONAL_BASIC T0085_HHRR_PERSONAL_BASIC { get; set; }
        public virtual T0550_HHRR_SYJ_Header T0550_HHRR_SYJ_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0552_HHRR_SYJ_Payments> T0552_HHRR_SYJ_Payments { get; set; }
    }
}
