//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0550_HHRR_SYJ_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0550_HHRR_SYJ_Header()
        {
            this.T0551_HHRR_SYJ_Items = new HashSet<T0551_HHRR_SYJ_Items>();
        }
    
        public int ID { get; set; }
        public System.DateTime Fecha { get; set; }
        public string PeriodoConta { get; set; }
        public string EstadoRegistro { get; set; }
        public string PeriodoQ { get; set; }
        public string Concepto { get; set; }
        public string Observacion { get; set; }
        public string LX { get; set; }
        public Nullable<decimal> MontoTotal { get; set; }
        public string Moneda { get; set; }
        public Nullable<decimal> MontoAdeudado { get; set; }
        public Nullable<int> NAS { get; set; }
        public string LogUser { get; set; }
        public System.DateTime LogDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0551_HHRR_SYJ_Items> T0551_HHRR_SYJ_Items { get; set; }
    }
}
