//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0552_HHRR_SYJ_Payments
    {
        public int IDPayment { get; set; }
        public int IDItem { get; set; }
        public string Shortname { get; set; }
        public string Moneda { get; set; }
        public decimal Importe { get; set; }
        public System.DateTime FechaPago { get; set; }
        public string GLAccount { get; set; }
        public string GLDescripcion { get; set; }
        public string Observacion { get; set; }
        public int NAS { get; set; }
        public string LogUser { get; set; }
        public System.DateTime LogDate { get; set; }
        public string DestinoPago { get; set; }
        public Nullable<int> IdCheque { get; set; }
    
        public virtual T0085_HHRR_PERSONAL_BASIC T0085_HHRR_PERSONAL_BASIC { get; set; }
        public virtual T0551_HHRR_SYJ_Items T0551_HHRR_SYJ_Items { get; set; }
    }
}
