//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0606_DOCUCONTACLI
    {
        public string IDDOC { get; set; }
        public string CODIGOAFIP { get; set; }
        public int SIGNCONTABILIZACION { get; set; }
        public string DESCRIPCION2 { get; set; }
        public string TIPODOC_SYSTEM { get; set; }
        public string DESCRIPCION_ENUM { get; set; }
        public bool ADDRECORDT208 { get; set; }
    
        public virtual T0605_DOCUCONFIG T0605_DOCUCONFIG { get; set; }
    }
}
