//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0601_DOCU_H
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0601_DOCU_H()
        {
            this.T0602_DOCU_S = new HashSet<T0602_DOCU_S>();
        }
    
        public int IDDOCU { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string MONE_ORI { get; set; }
        public Nullable<decimal> TC { get; set; }
        public string MES { get; set; }
        public string YEAR { get; set; }
        public string HeaderText { get; set; }
        public string DOCUTIPO { get; set; }
        public string REFE { get; set; }
        public Nullable<byte> ZTERM { get; set; }
        public Nullable<decimal> TOT_ORI { get; set; }
        public Nullable<decimal> TOT_ARS { get; set; }
        public string TIPO { get; set; }
        public string LOG_USER { get; set; }
        public Nullable<System.DateTime> FECHA_HOY { get; set; }
        public string ST { get; set; }
        public Nullable<bool> CK { get; set; }
        public Nullable<int> ALINK { get; set; }
        public string OR { get; set; }
        public Nullable<bool> RE { get; set; }
        public string ID { get; set; }
        public Nullable<decimal> NASX1 { get; set; }
        public Nullable<decimal> NASX2 { get; set; }
        public Nullable<System.DateTime> FechaOP { get; set; }
        public Nullable<bool> StatusCancel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0602_DOCU_S> T0602_DOCU_S { get; set; }
    }
}
