//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0602_DOCU_S
    {
        public int IDDOCU { get; set; }
        public int IDSEG { get; set; }
        public string MES { get; set; }
        public string YEAR { get; set; }
        public string CUENTA { get; set; }
        public string MONE_ORI { get; set; }
        public Nullable<decimal> TC { get; set; }
        public Nullable<decimal> IMPORTE_ORI { get; set; }
        public Nullable<decimal> IMPORTE_ARS { get; set; }
        public string SEGTEXT { get; set; }
        public string SEGTEXT2 { get; set; }
        public string DC { get; set; }
        public string DOCUTIPO { get; set; }
        public string REFE { get; set; }
        public string CLIENTE { get; set; }
        public string PROV { get; set; }
        public string LOG_USER { get; set; }
        public Nullable<System.DateTime> FECHA_HOY { get; set; }
        public Nullable<decimal> DEBE { get; set; }
        public Nullable<decimal> HABER { get; set; }
        public string GL { get; set; }
        public string CC { get; set; }
        public string ST { get; set; }
        public Nullable<bool> CK { get; set; }
        public string PERIODO { get; set; }
        public string TIPO { get; set; }
        public string TCODE { get; set; }
        public string GLL3 { get; set; }
        public Nullable<int> ALINK { get; set; }
        public string GLORI { get; set; }
        public string REF_ALT_TBLID { get; set; }
        public string REF_ALT_IDNUM { get; set; }
        public string REF_ALT_IDTXT { get; set; }
        public string CLIPROV_DESC { get; set; }
        public string UPDUSER { get; set; }
        public Nullable<decimal> KGMAT { get; set; }
        public string MATERIAL { get; set; }
        public Nullable<int> ID40 { get; set; }
        public Nullable<decimal> NASX1 { get; set; }
        public Nullable<decimal> NASX2 { get; set; }
        public Nullable<System.DateTime> HORA_OP { get; set; }
    
        public virtual T0601_DOCU_H T0601_DOCU_H { get; set; }
    }
}
