//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0603_DOCTYPES
    {
        public string IDDOC { get; set; }
        public string Shortname { get; set; }
        public string DESCRIPCION { get; set; }
        public string AFIP_CODE { get; set; }
        public string DefaultDocumentDescription { get; set; }
        public Nullable<bool> AllowL1 { get; set; }
        public Nullable<bool> AllowL2 { get; set; }
    }
}
