//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0807QMIDetail
    {
        public int IdCounterH2 { get; set; }
        public int IdRec { get; set; }
        public int IdCounterDetail { get; set; }
        public string Metodo { get; set; }
        public bool MetodoAdded { get; set; }
        public string IdPlan { get; set; }
        public string Material { get; set; }
        public decimal KGInspeccion { get; set; }
        public string ValorMin { get; set; }
        public string ValorMax { get; set; }
        public string ValorStd { get; set; }
        public string ValorMedido { get; set; }
        public string Resultado { get; set; }
        public bool CQAprobado { get; set; }
        public string UserLog { get; set; }
        public System.DateTime FechaLog { get; set; }
        public string ComentarioDetail { get; set; }
        public Nullable<System.DateTime> FechaResultado { get; set; }
    
        public virtual T0800_QMMetodosInspeccion T0800_QMMetodosInspeccion { get; set; }
        public virtual T0806_QMIRecordH2 T0806_QMIRecordH2 { get; set; }
    }
}
