//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0800_QMMetodosInspeccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0800_QMMetodosInspeccion()
        {
            this.T0802_QMMasterIPDetail = new HashSet<T0802_QMMasterIPDetail>();
            this.T0807QMIDetail = new HashSet<T0807QMIDetail>();
        }
    
        public string IdMetodo { get; set; }
        public string Descripcion { get; set; }
        public bool Activo { get; set; }
        public string ValorUnit { get; set; }
        public string ValorType { get; set; }
        public string Documentacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0802_QMMasterIPDetail> T0802_QMMasterIPDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0807QMIDetail> T0807QMIDetail { get; set; }
    }
}
