//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0802_QMMasterIPDetail
    {
        public string IDPLAN { get; set; }
        public string METODO { get; set; }
        public bool ACTIVO { get; set; }
        public string ValorMin { get; set; }
        public string ValorMax { get; set; }
        public string ValorStd { get; set; }
        public string Observacion { get; set; }
    
        public virtual T0800_QMMetodosInspeccion T0800_QMMetodosInspeccion { get; set; }
        public virtual T0801_QMMasterIPHeader T0801_QMMasterIPHeader { get; set; }
    }
}
