//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0805_QMIRecordH1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0805_QMIRecordH1()
        {
            this.T0806_QMIRecordH2 = new HashSet<T0806_QMIRecordH2>();
        }
    
        public int IdIRec { get; set; }
        public string Material { get; set; }
        public string IdPlan { get; set; }
        public string Lote { get; set; }
        public System.DateTime FechaLote { get; set; }
        public string Origen { get; set; }
        public Nullable<int> IdOrigen { get; set; }
        public string IdOrigenTexto { get; set; }
        public string TipoRecord { get; set; }
        public decimal KGTotalBatch { get; set; }
        public string ComentarioH1 { get; set; }
        public string EstadoPlanGeneral { get; set; }
        public string LogUser { get; set; }
        public System.DateTime LogDate { get; set; }
        public bool InspeccionOK { get; set; }
        public string DocID { get; set; }
        public string DocNumber { get; set; }
    
        public virtual T0801_QMMasterIPHeader T0801_QMMasterIPHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0806_QMIRecordH2> T0806_QMIRecordH2 { get; set; }
    }
}
