//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0806_QMIRecordH2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0806_QMIRecordH2()
        {
            this.T0807QMIDetail = new HashSet<T0807QMIDetail>();
        }
    
        public int IdCounter { get; set; }
        public int IdRec { get; set; }
        public string IdPlan { get; set; }
        public string Material { get; set; }
        public string Lote { get; set; }
        public decimal KGInspeccion { get; set; }
        public string EstadoInspeccion { get; set; }
        public System.DateTime FechaInspeccion { get; set; }
        public string ResponsableCQ { get; set; }
        public string LogUser { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public bool PlanEditado { get; set; }
        public string ComentarioH2 { get; set; }
        public bool AprobadoOk { get; set; }
        public bool AprobadoDudoso { get; set; }
    
        public virtual T0805_QMIRecordH1 T0805_QMIRecordH1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0807QMIDetail> T0807QMIDetail { get; set; }
    }
}
