//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0821_CQ1I
    {
        public Nullable<double> IDCQ1 { get; set; }
        public Nullable<double> IDSEQ { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string USUARIO { get; set; }
        public string NOTA1 { get; set; }
        public bool RESUELTO { get; set; }
        public string LOGUSER { get; set; }
        public Nullable<System.DateTime> LOGDATE { get; set; }
        public byte[] ATTACH { get; set; }
    }
}
