//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0820_CQ1H
    {
        public int IDCQ1 { get; set; }
        public string USR_GENERADOR { get; set; }
        public string USR_AFECTADO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string DESCRIPCION_CQ1 { get; set; }
        public string ESTADO_CQ1 { get; set; }
        public Nullable<System.DateTime> FECHA_CIERRE { get; set; }
        public string USR_CIERRE { get; set; }
        public string USR_ASIGNADO { get; set; }
    }
}
