//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T1011_GESPA_MENSAJES
    {
        public int idRecord { get; set; }
        public int idVendor { get; set; }
        public System.DateTime FechaMensaje { get; set; }
        public string Mensaje { get; set; }
        public Nullable<bool> MensajeRecibido { get; set; }
        public Nullable<bool> MensajeTecser { get; set; }
    }
}
