//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T1010_GESPA_H
    {
        public int idVendor { get; set; }
        public string vendorRazonSocial { get; set; }
        public bool ReclamaPago { get; set; }
        public bool ConfirmaPago { get; set; }
        public Nullable<System.DateTime> FechaPagoConfirmada { get; set; }
        public string HoraPago { get; set; }
        public string StatusPago { get; set; }
        public string NumeroOrdenPagoConfirmada { get; set; }
    }
}
