//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T1206_CobranzaConvertirItems
    {
        public int idCobTem { get; set; }
        public int idItem { get; set; }
        public string CuentaItem { get; set; }
        public string GLItem { get; set; }
        public string MonedaItem { get; set; }
        public Nullable<decimal> TipoCambio { get; set; }
        public Nullable<decimal> ImporteMoneda { get; set; }
        public decimal ImporteRecibo { get; set; }
        public string NumeroCheque { get; set; }
        public string NumeroBanco { get; set; }
        public string Cuit { get; set; }
        public string NumeroCuenta { get; set; }
        public string CodigoPostalCheque { get; set; }
        public Nullable<System.DateTime> FechaAcreditacion { get; set; }
        public Nullable<int> IdCheque { get; set; }
        public bool ChequeInterior { get; set; }
        public bool isEcheque { get; set; }
        public string RetencionProvincia { get; set; }
        public Nullable<decimal> RetencionAlicuota { get; set; }
    }
}
