//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T1205_CobranzaConvertirHeader
    {
        public int idCobTemp { get; set; }
        public int idCliente { get; set; }
        public Nullable<int> idCobReal { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string UserIngreso { get; set; }
        public string ClienteRazonSocial { get; set; }
        public string LX { get; set; }
        public string Moneda { get; set; }
        public Nullable<decimal> ImporteRecibo { get; set; }
        public Nullable<System.DateTime> ConvertidoFecha { get; set; }
        public string ConvertidoUser { get; set; }
        public string StatusRecibo { get; set; }
        public string NumeroReciboProvisorio { get; set; }
        public string NumeroReciboInterno { get; set; }
        public string Observaciones { get; set; }
        public string Cobrador { get; set; }
        public Nullable<decimal> Tc { get; set; }
    }
}
