//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T992_DOCUMENTOS_CONFIG
    {
        public int ID { get; set; }
        public string NumUltRemitoL1Prefix { get; set; }
        public Nullable<int> NumUltRemitoL1 { get; set; }
        public string NumUltRemitoL2Prefix { get; set; }
        public Nullable<int> NumUltRemitoL2 { get; set; }
    }
}
