//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AFIP_CAE
    {
        public string CAENUM { get; set; }
        public Nullable<System.DateTime> CAEVTO { get; set; }
        public string TIPODOC { get; set; }
        public string PTOVTA { get; set; }
        public string NUMDOC { get; set; }
        public string CUIT { get; set; }
        public string MONEDA { get; set; }
        public Nullable<System.DateTime> FECHADOC { get; set; }
        public string Cliente { get; set; }
        public Nullable<decimal> NETO { get; set; }
        public Nullable<decimal> BRUTO { get; set; }
        public Nullable<decimal> IVA10 { get; set; }
        public Nullable<decimal> IVA21 { get; set; }
        public Nullable<decimal> PERCIIBB_MONTO { get; set; }
        public string NUMDOC_C { get; set; }
        public Nullable<System.DateTime> Fecha_AFIP { get; set; }
        public Nullable<bool> EnviadaAFIP { get; set; }
        public Nullable<bool> Confirmada { get; set; }
        public Nullable<bool> Activa { get; set; }
        public Nullable<int> Idtrto { get; set; }
        public Nullable<int> ASIENTO { get; set; }
        public int IDFACTURA { get; set; }
        public string RESULTADO_AFIP { get; set; }
        public string ERROR_AFIP { get; set; }
        public string METODO_CAE { get; set; }
        public Nullable<bool> IMPRESA { get; set; }
        public string PERCIIBB { get; set; }
        public Nullable<decimal> PERCIIBB_ALIC { get; set; }
    }
}
