//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TApplicationConfig
    {
        public string IdKey { get; set; }
        public string ValueType { get; set; }
        public Nullable<int> ValueInt { get; set; }
        public string ValueString { get; set; }
        public string Descripcion { get; set; }
    }
}
