//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAUX_G3
    {
        public Nullable<int> IDCLI_OLD { get; set; }
        public int IDCLI { get; set; }
        public Nullable<System.DateTime> ULTIMALL { get; set; }
        public Nullable<System.DateTime> LlamarNuevo { get; set; }
        public bool PasarACobrar { get; set; }
        public Nullable<System.DateTime> PasarACobrarFecha { get; set; }
        public Nullable<decimal> ULTSALDO { get; set; }
        public Nullable<decimal> ULTSALDOL2 { get; set; }
        public Nullable<System.DateTime> ULTPAGO { get; set; }
        public Nullable<System.DateTime> FCONC_L1 { get; set; }
        public Nullable<System.DateTime> FCONC_L2 { get; set; }
        public Nullable<int> SCONC_L1 { get; set; }
        public Nullable<int> SCONC_L2 { get; set; }
        public string COMENTL1 { get; set; }
        public string COMENTL2 { get; set; }
        public bool REQCONL1 { get; set; }
        public bool REQCONL2 { get; set; }
        public string LOG_USER_CONCI { get; set; }
        public string LOG_FECHA_CONCI { get; set; }
        public string XADD_USER { get; set; }
        public string XADD_REASON { get; set; }
        public string XADD_TCODE { get; set; }
        public string XADD_RESPUESTA { get; set; }
        public bool XADD_CK { get; set; }
        public string MSGCOBRAR { get; set; }
        public bool SELECCION_COB { get; set; }
    }
}
