//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLConfigForm
    {
        public string IDFUNCION { get; set; }
        public int IDWrite { get; set; }
        public Nullable<int> FXStep { get; set; }
        public Nullable<int> IDRead { get; set; }
        public int IDX { get; set; }
        public string D1 { get; set; }
        public string D2 { get; set; }
        public string D3 { get; set; }
        public string Desc1 { get; set; }
        public string Desc2 { get; set; }
        public string FX { get; set; }
        public string DescripcionGeneral { get; set; }
    }
}
