//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempT403
    {
        public int IDINT { get; set; }
        public int IDPROV { get; set; }
        public string PROVRS { get; set; }
        public string PRTAX1 { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string MON { get; set; }
        public string TFACTURA { get; set; }
        public string NFACTURA { get; set; }
        public Nullable<decimal> IMPORI { get; set; }
        public Nullable<decimal> TC { get; set; }
        public string TIPO { get; set; }
        public Nullable<decimal> BRUTO { get; set; }
        public Nullable<decimal> DTO { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
        public Nullable<decimal> BaseImponible { get; set; }
        public Nullable<decimal> IVA10 { get; set; }
        public Nullable<decimal> IVA21 { get; set; }
        public Nullable<decimal> IVA27 { get; set; }
        public Nullable<decimal> TOTALIVA { get; set; }
        public Nullable<decimal> PerIVA { get; set; }
        public Nullable<decimal> PerIVA_Alicuota { get; set; }
        public Nullable<decimal> RETIVA { get; set; }
        public Nullable<decimal> PerIIBB { get; set; }
        public Nullable<decimal> PerIIBB_Alicuota { get; set; }
        public string PerIIBB_TXT { get; set; }
        public Nullable<decimal> RETIIBB { get; set; }
        public Nullable<decimal> ImpuestoMunicipal { get; set; }
        public Nullable<decimal> ImpuestoProvincial { get; set; }
        public Nullable<decimal> IMPINT { get; set; }
        public Nullable<decimal> IMPOTR { get; set; }
        public string LOGUSER { get; set; }
        public Nullable<System.DateTime> LOGDATE { get; set; }
        public Nullable<int> NASIENTO { get; set; }
        public string TCODE { get; set; }
        public Nullable<int> IDCTACTE { get; set; }
        public string GLAP { get; set; }
        public Nullable<decimal> CANTKG { get; set; }
        public string OBSERVACION { get; set; }
        public Nullable<decimal> IdFacturaX { get; set; }
        public Nullable<decimal> PerGA_Alicuota { get; set; }
        public Nullable<decimal> PerGS { get; set; }
        public Nullable<decimal> SALDOIMPAGO { get; set; }
        public Nullable<decimal> ConceptosNoGravados { get; set; }
        public Nullable<decimal> TotalImpuestosVarios { get; set; }
        public Nullable<decimal> NETO { get; set; }
        public string StatusDocumento { get; set; }
    }
}
