//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TL001_MsgLog
    {
        public decimal IdLog { get; set; }
        public System.DateTime FechaLog { get; set; }
        public string UserLog { get; set; }
        public string ComputerLog { get; set; }
        public string TCode { get; set; }
        public string Mensaje1 { get; set; }
        public string Mensaje2 { get; set; }
        public string ErrorCode { get; set; }
    }
}
