//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLogTcode
    {
        public decimal IdLog { get; set; }
        public string Tcode { get; set; }
        public string Username { get; set; }
        public string Computer { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string IPLog { get; set; }
    }
}
