//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMensajes01
    {
        public int idMensaje { get; set; }
        public string UserSent { get; set; }
        public string UserTo1 { get; set; }
        public string UserTo2 { get; set; }
        public string UserTo3 { get; set; }
        public string Mensaje { get; set; }
        public bool Leido { get; set; }
        public System.DateTime LogEnviado { get; set; }
        public System.DateTime LogLeido { get; set; }
    }
}
