//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSecurityLog
    {
        public int idLog { get; set; }
        public string TCode { get; set; }
        public string Username { get; set; }
        public string Computer { get; set; }
        public string IP { get; set; }
        public string Alert { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
    }
}
