//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsecurityLogCheck
    {
        public int idMsg { get; set; }
        public string Tcode { get; set; }
        public string RoleCheck { get; set; }
        public string Username { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool AccessGranted { get; set; }
        public string Equipo { get; set; }
        public string IP { get; set; }
        public string Mensaje { get; set; }
    }
}
