//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSecRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSecRole()
        {
            this.TSecRoleAssignment = new HashSet<TSecRoleAssignment>();
        }
    
        public string RoleName { get; set; }
        public string RoleDescription { get; set; }
        public bool IsTcode { get; set; }
        public bool isFunction { get; set; }
        public bool Activo { get; set; }
        public string Modulo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSecRoleAssignment> TSecRoleAssignment { get; set; }
    }
}
