//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSecRoleAssignment
    {
        public string idUser { get; set; }
        public string idRole { get; set; }
        public bool idActivo { get; set; }
    
        public virtual TSecRole TSecRole { get; set; }
        public virtual TSecUsr TSecUsr { get; set; }
    }
}
