//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTAXRetPerData
    {
        public int IDREC { get; set; }
        public string TAXID { get; set; }
        public string PC { get; set; }
        public Nullable<int> IDPC { get; set; }
        public Nullable<decimal> COEF1 { get; set; }
        public Nullable<decimal> ALICUOTA { get; set; }
        public Nullable<decimal> BASE1 { get; set; }
        public Nullable<System.DateTime> FECHA_D { get; set; }
        public Nullable<System.DateTime> FECHA_H { get; set; }
        public bool ACTIVO { get; set; }
        public bool EXENTO { get; set; }
        public string EXENTO_CERTIFICADO { get; set; }
        public Nullable<System.DateTime> FECHA_EXENTO_D { get; set; }
        public Nullable<System.DateTime> FECHA_EXENTO_H { get; set; }
        public string CUIT { get; set; }
        public string Periodo { get; set; }
    }
}
