//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class USR005
    {
        public int ID { get; set; }
        public string TCODE { get; set; }
        public string ROLE { get; set; }
        public string ACCION { get; set; }
        public string USERLOG { get; set; }
        public Nullable<System.DateTime> DATELOG { get; set; }
        public string COMPUTER { get; set; }
    }
}
