//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class USR003
    {
        public int ID { get; set; }
        public string TCODE { get; set; }
        public string ROLE { get; set; }
        public bool ACTIVO { get; set; }
        public string DESCRIPCION { get; set; }
        public string DETALLE { get; set; }
        public string A { get; set; }
        public string B { get; set; }
        public string C { get; set; }
    }
}
