//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class XREGISTER
    {
        public int IDT { get; set; }
        public string IDC { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string XMES { get; set; }
        public string XYEAR { get; set; }
        public string Tdoc { get; set; }
        public string Ref { get; set; }
        public string PC { get; set; }
        public Nullable<int> PCID { get; set; }
        public string Entidad { get; set; }
        public string Descripcion { get; set; }
        public string CCosto { get; set; }
        public string XTransf { get; set; }
        public string Moneda { get; set; }
        public Nullable<decimal> Monto_I { get; set; }
        public Nullable<decimal> Monto_E { get; set; }
        public string LogUser { get; set; }
        public Nullable<System.DateTime> LogFecha { get; set; }
        public string ST { get; set; }
        public string CH_BCO { get; set; }
        public Nullable<System.DateTime> CH_FEC { get; set; }
        public Nullable<int> CH_ID { get; set; }
        public string TIPO { get; set; }
        public string CC { get; set; }
        public Nullable<int> NAS { get; set; }
        public string TCODE { get; set; }
    }
}
